return {
  version = "1.2",
  luaversion = "5.1",
  tiledversion = "2020.01.22",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 39,
  height = 17,
  tilewidth = 16,
  tileheight = 16,
  nextlayerid = 53,
  nextobjectid = 200,
  properties = {},
  tilesets = {
    {
      name = "UIpackSheet_transparent",
      firstgid = 1,
      tilewidth = 16,
      tileheight = 16,
      spacing = 2,
      margin = 0,
      columns = 30,
      image = "../tileset/Tilemap/UIpackSheet_transparent.png",
      imagewidth = 538,
      imageheight = 592,
      objectalignment = "unspecified",
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 16,
        height = 16
      },
      properties = {},
      terrains = {},
      tilecount = 990,
      tiles = {}
    },
    {
      name = "roguelikeCity",
      firstgid = 991,
      tilewidth = 16,
      tileheight = 16,
      spacing = 1,
      margin = 0,
      columns = 37,
      image = "../tileset/Tilemap/roguelikeCity.png",
      imagewidth = 628,
      imageheight = 475,
      objectalignment = "unspecified",
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 16,
        height = 16
      },
      properties = {},
      terrains = {},
      tilecount = 1036,
      tiles = {}
    },
    {
      name = "functionsTextTiles",
      firstgid = 2027,
      tilewidth = 16,
      tileheight = 16,
      spacing = 0,
      margin = 0,
      columns = 30,
      image = "../graphics/functionsTextTiles.png",
      imagewidth = 480,
      imageheight = 480,
      objectalignment = "unspecified",
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 16,
        height = 16
      },
      properties = {},
      terrains = {},
      tilecount = 900,
      tiles = {}
    },
    {
      name = "test",
      firstgid = 2927,
      tilewidth = 16,
      tileheight = 16,
      spacing = 0,
      margin = 0,
      columns = 27,
      image = "../tileset/Tilemap/test.png",
      imagewidth = 432,
      imageheight = 288,
      objectalignment = "unspecified",
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 16,
        height = 16
      },
      properties = {},
      terrains = {},
      tilecount = 486,
      tiles = {}
    }
  },
  layers = {
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 50,
      name = "Tile Layer 21",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxbxM7AsIgK+BcbA8MZIHYGslVYqGMmtTAtwKjbRt026rZRt426bdRto24bddtAuU2eHYEHGwAAvvzMEA=="
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 51,
      name = "Tile Layer 22",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJztlEEKACAIBLv3v8D/fyQ6BCGWGrR6aEA6FDguUim5obqvdqhxnxWEmzez6YRwa84eEW5abtwJ6abll8FNyk16592FG8jYM9JtPfmeUbXP8NJNI8pt95/xQrt5QblZ85Ly+3ysdHA5Kr4="
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 14,
      name = "info",
      visible = true,
      opacity = 1,
      offsetx = 48,
      offsety = 16,
      properties = {
        ["F0"] = 5,
        ["F1"] = 0,
        ["blueTile"] = true,
        ["door"] = false,
        ["face"] = "right",
        ["fruit"] = true,
        ["fruitsTotal"] = 5,
        ["grass"] = true,
        ["greyTile"] = true,
        ["numFunc"] = 1,
        ["totalSize"] = 5,
        ["yellowTile"] = false
      },
      encoding = "base64",
      compression = "zlib",
      data = "eJztwTEBAAAAwqD1T20JT6AAAOBjClwAAQ=="
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 36,
      name = "buttonsSecondRow",
      visible = true,
      opacity = 1,
      offsetx = 48,
      offsety = 16,
      properties = {
        ["blue"] = "blueTile",
        ["grey"] = "greyTile"
      },
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYKAOUGFhYFjETjmmBRh126jbRt02+N3mCXSbFxUwLcBKNlTsAgwDZ3bSaXq4jVw8Ut2WxY7fbkLytHTbYA63we42YvMlurvQ86k8O/l4qIQbLQAAqeKvgA=="
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 37,
      name = "buttonsThirdRow",
      visible = true,
      opacity = 1,
      offsetx = 48,
      offsety = 16,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFo2AUjIJRQCxwZmdgCAXiMDLoUTAKRsEoAIHhXoYAAO/3Cmk="
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 44,
      name = "more",
      visible = true,
      opacity = 1,
      offsetx = 48,
      offsety = 16,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJztwTEBAAAAwqD1T20JT6AAAOBjClwAAQ=="
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 47,
      name = "open",
      visible = true,
      opacity = 1,
      offsetx = 48,
      offsety = 16,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJztwTEBAAAAwqD1T20JT6AAAOBjClwAAQ=="
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 43,
      name = "street",
      visible = true,
      opacity = 1,
      offsetx = 48,
      offsety = 16,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYKAM/GJjYFjJRqEhNAKjbiMPjLqNPDDqNvLAqNvIA6NuIw/IsA+0C0bBSAIrB3FeoCUAAIZJFAc="
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 42,
      name = "details",
      visible = true,
      opacity = 1,
      offsetx = 48,
      offsety = 16,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYCAf/GJjYDgDxM7sFBhCIzDqNvLAqNvIA6NuIw+Muo08AHPbR7aBdgkmgLltMAKQ22yB8blyELoPFm6D3W2DzX2D2W0rB7HbaA0AamwlSw=="
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 41,
      name = "cars",
      visible = true,
      opacity = 1,
      offsetx = 48,
      offsety = 16,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYCAfzGJjYJjNRoEBNAT7ge46MEjdNgpGwSgY2uAAOwPDQSCeASxjZiKVMzpAMV0kcZg6eoKnQPueAfFeoP37kNwWCBQLQhKHqRsFo4ASoAdMQ/pAfAiID7Mj2gWDoX0QDHRPCBA/B+IX7Ih2wWj7gPYAAPs9GmU="
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 12,
      name = "text",
      visible = true,
      opacity = 1,
      offsetx = 64,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJzt0DkKgEAQRNHKxnGOoLdyX8/qfVxTBcHKDMS4HekPDzosGvh/ewAclFggpYxyKqikimpqqKWOeiu9Wr7RABPNtNBppBfdrR/a8tYQApEDYve8pdo8+JumaZrmdxegRhBN"
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 22,
      name = "fruit1",
      visible = true,
      opacity = 1,
      offsetx = 0.363636,
      offsety = -3,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBie4DvXQLtgFIyCUTAKRsEoGAWjYOQBAJhdAQI="
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 23,
      name = "fruit2",
      visible = true,
      opacity = 1,
      offsetx = 0.363636,
      offsety = -3,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFo2AUjIJRMApGwXAH37kG2gWjYKQAAHjcAQI="
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 24,
      name = "fruit3",
      visible = true,
      opacity = 1,
      offsetx = 0.363636,
      offsety = -3,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFo4CB4TvXQLtgFIyCUTAKRsEoGAXDAQAAZx4BAg=="
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 25,
      name = "fruit4",
      visible = true,
      opacity = 1,
      offsetx = 0.363636,
      offsety = -3,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFo2AUjIJRMAqGHvjONdAuGAWjYBRgAwCqGwEC"
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 26,
      name = "fruit5",
      visible = true,
      opacity = 1,
      offsetx = 0.363636,
      offsety = -3,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFo2AUjALagu9cA+2CUTAKRsEoGAX0AgAEoAEC"
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 2,
      name = "buttons",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJztzskNggAQQNE5w0Fc2nBtAxXbcIF2XKAN1zYUtQ1APfMTGuBgwhzmJ+/+RSzLsqx/tnVEdtjjgBiJ0/RV1ZGPE8644Iqbkrc7Hw+keOKFt5K3jI8cBT744qfkreWKeGijgy56btNXVX0+BhhihDEmSt58PqaYYY4ACyVvSz5WWGODEJGStzqVXZ4acQ=="
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 32,
      name = "answer",
      visible = false,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {
        ["numObejcts"] = 6
      },
      objects = {
        {
          id = 19,
          name = "answer1",
          type = "",
          shape = "rectangle",
          x = 383.506,
          y = 79.9692,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 20,
          name = "answer2",
          type = "",
          shape = "rectangle",
          x = 407.477,
          y = 79.9958,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 21,
          name = "answer3",
          type = "",
          shape = "rectangle",
          x = 431.381,
          y = 79.9416,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 26,
          name = "answer4",
          type = "",
          shape = "rectangle",
          x = 455.518,
          y = 80.0888,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 27,
          name = "answer5",
          type = "",
          shape = "rectangle",
          x = 479.627,
          y = 80.0568,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 33,
      name = "grass",
      visible = false,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {
        ["numObjects"] = 13
      },
      objects = {
        {
          id = 31,
          name = "grass1",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 228,
          width = 330.364,
          height = 56.773,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 32,
          name = "grass2",
          type = "",
          shape = "rectangle",
          x = 0.167,
          y = -0.2423,
          width = 12.667,
          height = 316.742,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 33,
          name = "grass3",
          type = "",
          shape = "rectangle",
          x = 261.042,
          y = -4.46875,
          width = 112.583,
          height = 272,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 34,
          name = "grass4",
          type = "",
          shape = "rectangle",
          x = -2,
          y = -11.5,
          width = 304.5,
          height = 24.25,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 35,
          name = "grass5",
          type = "",
          shape = "rectangle",
          x = 68.5,
          y = 99,
          width = 6,
          height = 71.5,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 53,
          name = "grass6",
          type = "",
          shape = "rectangle",
          x = 197.5,
          y = 69.75,
          width = 5.33333,
          height = 100.5,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 54,
          name = "grass7",
          type = "",
          shape = "rectangle",
          x = 79,
          y = 164.75,
          width = 121.333,
          height = 6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 55,
          name = "grass8",
          type = "",
          shape = "rectangle",
          x = 83,
          y = 101.25,
          width = 84.8333,
          height = 5,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 56,
          name = "grass9",
          type = "",
          shape = "rectangle",
          x = 228.5,
          y = 42.25,
          width = 5.16667,
          height = 161,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 58,
          name = "grass13",
          type = "",
          shape = "rectangle",
          x = 40.75,
          y = 197.125,
          width = 192,
          height = 5,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 59,
          name = "grass12",
          type = "",
          shape = "rectangle",
          x = 38.75,
          y = 73.125,
          width = 4,
          height = 128,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 60,
          name = "grass11",
          type = "",
          shape = "rectangle",
          x = 37.75,
          y = 69.125,
          width = 165,
          height = 5,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 61,
          name = "grass10",
          type = "",
          shape = "rectangle",
          x = 14.25,
          y = 37.125,
          width = 220,
          height = 5.5,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 35,
      name = "player",
      visible = false,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      objects = {
        {
          id = 37,
          name = "player",
          type = "",
          shape = "rectangle",
          x = 16,
          y = 16,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 52,
      name = "greyTile",
      visible = false,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {
        ["numObjects"] = 58
      },
      objects = {
        {
          id = 137,
          name = "greyTile1",
          type = "",
          shape = "rectangle",
          x = 23.4281,
          y = 20.7424,
          width = 0.363636,
          height = 0.363636,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 138,
          name = "greyTile2",
          type = "",
          shape = "rectangle",
          x = 43.2421,
          y = 19.9596,
          width = 0.363636,
          height = 0.363636,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 139,
          name = "greyTile3",
          type = "",
          shape = "rectangle",
          x = 55.1611,
          y = 19.9162,
          width = 0.363636,
          height = 0.363636,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 140,
          name = "greyTile4",
          type = "",
          shape = "rectangle",
          x = 74.9751,
          y = 19.1334,
          width = 0.363636,
          height = 0.363636,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 141,
          name = "greyTile5",
          type = "",
          shape = "rectangle",
          x = 90.9521,
          y = 19.1879,
          width = 0.363636,
          height = 0.363636,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 142,
          name = "greyTile6",
          type = "",
          shape = "rectangle",
          x = 102.871,
          y = 19.1445,
          width = 0.363636,
          height = 0.363636,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 143,
          name = "greyTile7",
          type = "",
          shape = "rectangle",
          x = 122.685,
          y = 18.3617,
          width = 0.363636,
          height = 0.363636,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 144,
          name = "greyTile23",
          type = "",
          shape = "rectangle",
          x = 27.2854,
          y = 51.5629,
          width = 0.363636,
          height = 0.363636,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 145,
          name = "greyTile24",
          type = "",
          shape = "rectangle",
          x = 43.8294,
          y = 51.3945,
          width = 0.363636,
          height = 0.363636,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 146,
          name = "greyTile25",
          type = "",
          shape = "rectangle",
          x = 60.1434,
          y = 50.9867,
          width = 0.363636,
          height = 0.363636,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 147,
          name = "greyTile26",
          type = "",
          shape = "rectangle",
          x = 77.0354,
          y = 51.0629,
          width = 0.363636,
          height = 0.363636,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 148,
          name = "greyTile27",
          type = "",
          shape = "rectangle",
          x = 92.5794,
          y = 51.7695,
          width = 0.363636,
          height = 0.363636,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 149,
          name = "greyTile28",
          type = "",
          shape = "rectangle",
          x = 108.643,
          y = 51.6117,
          width = 0.363636,
          height = 0.363636,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 150,
          name = "greyTile41",
          type = "",
          shape = "rectangle",
          x = 53.0506,
          y = 84.3773,
          width = 0.363636,
          height = 0.363636,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 151,
          name = "greyTile42",
          type = "",
          shape = "rectangle",
          x = 68.7877,
          y = 85.0612,
          width = 0.363636,
          height = 0.363636,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 152,
          name = "greyTile44",
          type = "",
          shape = "rectangle",
          x = 104.852,
          y = 84.5284,
          width = 0.363636,
          height = 0.363636,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 153,
          name = "greyTile51",
          type = "",
          shape = "rectangle",
          x = 92.7248,
          y = 119.226,
          width = 0.363636,
          height = 0.363636,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 154,
          name = "greyTile52",
          type = "",
          shape = "rectangle",
          x = 105.598,
          y = 124.353,
          width = 0.363636,
          height = 0.363636,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 156,
          name = "greyTile43",
          type = "",
          shape = "rectangle",
          x = 84.0075,
          y = 84.9188,
          width = 0.363636,
          height = 0.363636,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 157,
          name = "greyTile50",
          type = "",
          shape = "rectangle",
          x = 82.1819,
          y = 155.244,
          width = 0.363636,
          height = 0.363636,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 158,
          name = "greyTile49",
          type = "",
          shape = "rectangle",
          x = 147.015,
          y = 157.259,
          width = 0.363636,
          height = 0.363636,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 159,
          name = "greyTile48",
          type = "",
          shape = "rectangle",
          x = 163.561,
          y = 157.374,
          width = 0.363636,
          height = 0.363636,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 160,
          name = "greyTile47",
          type = "",
          shape = "rectangle",
          x = 188.629,
          y = 156.964,
          width = 0.363636,
          height = 0.363636,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 161,
          name = "greyTile45",
          type = "",
          shape = "rectangle",
          x = 185.985,
          y = 87.1913,
          width = 0.363636,
          height = 0.363636,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 162,
          name = "greyTile46",
          type = "",
          shape = "rectangle",
          x = 186.985,
          y = 103.691,
          width = 0.363636,
          height = 0.363636,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 163,
          name = "greyTile29",
          type = "",
          shape = "rectangle",
          x = 220.61,
          y = 54.3163,
          width = 0.363636,
          height = 0.363636,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 164,
          name = "greyTile30",
          type = "",
          shape = "rectangle",
          x = 220.36,
          y = 75.4413,
          width = 0.363636,
          height = 0.363636,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 165,
          name = "greyTile31",
          type = "",
          shape = "rectangle",
          x = 220.36,
          y = 91.1913,
          width = 0.363636,
          height = 0.363636,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 166,
          name = "greyTile32",
          type = "",
          shape = "rectangle",
          x = 220.61,
          y = 106.691,
          width = 0.363636,
          height = 0.363636,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 167,
          name = "greyTile8",
          type = "",
          shape = "rectangle",
          x = 252.348,
          y = 28.0095,
          width = 0.363636,
          height = 0.363636,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 168,
          name = "greyTile9",
          type = "",
          shape = "rectangle",
          x = 251.917,
          y = 40.2822,
          width = 0.363636,
          height = 0.363636,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 169,
          name = "greyTile10",
          type = "",
          shape = "rectangle",
          x = 252.212,
          y = 59.8731,
          width = 0.363636,
          height = 0.363636,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 170,
          name = "greyTile11",
          type = "",
          shape = "rectangle",
          x = 251.985,
          y = 75.9413,
          width = 0.363636,
          height = 0.363636,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 171,
          name = "greyTile12",
          type = "",
          shape = "rectangle",
          x = 251.485,
          y = 89.1913,
          width = 0.363636,
          height = 0.363636,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 172,
          name = "greyTile13",
          type = "",
          shape = "rectangle",
          x = 251.735,
          y = 103.941,
          width = 0.363636,
          height = 0.363636,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 173,
          name = "greyTile33",
          type = "",
          shape = "rectangle",
          x = 211.443,
          y = 188.858,
          width = 0.363636,
          height = 0.363636,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 174,
          name = "greyTile34",
          type = "",
          shape = "rectangle",
          x = 194.443,
          y = 188.483,
          width = 0.363636,
          height = 0.363636,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 175,
          name = "greyTile35",
          type = "",
          shape = "rectangle",
          x = 179.193,
          y = 188.983,
          width = 0.363636,
          height = 0.363636,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 176,
          name = "greyTile36",
          type = "",
          shape = "rectangle",
          x = 162.568,
          y = 188.858,
          width = 0.363636,
          height = 0.363636,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 177,
          name = "greyTile37",
          type = "",
          shape = "rectangle",
          x = 146.318,
          y = 188.358,
          width = 0.363636,
          height = 0.363636,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 178,
          name = "greyTile14",
          type = "",
          shape = "rectangle",
          x = 178.311,
          y = 217.259,
          width = 0.363636,
          height = 0.363636,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 179,
          name = "greyTile15",
          type = "",
          shape = "rectangle",
          x = 162.856,
          y = 216.919,
          width = 0.363636,
          height = 0.363636,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 180,
          name = "greyTile16",
          type = "",
          shape = "rectangle",
          x = 146.788,
          y = 217.373,
          width = 0.363636,
          height = 0.363636,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 181,
          name = "greyTile17",
          type = "",
          shape = "rectangle",
          x = 132.22,
          y = 218.35,
          width = 0.363636,
          height = 0.363636,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 182,
          name = "greyTile18",
          type = "",
          shape = "rectangle",
          x = 114.879,
          y = 217.623,
          width = 0.363636,
          height = 0.363636,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 183,
          name = "greyTile38",
          type = "",
          shape = "rectangle",
          x = 50.8183,
          y = 183.108,
          width = 0.363636,
          height = 0.363636,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 184,
          name = "greyTile39",
          type = "",
          shape = "rectangle",
          x = 51.5683,
          y = 165.358,
          width = 0.363636,
          height = 0.363636,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 185,
          name = "greyTile40",
          type = "",
          shape = "rectangle",
          x = 51.3183,
          y = 149.358,
          width = 0.363636,
          height = 0.363636,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 186,
          name = "greyTile19",
          type = "",
          shape = "rectangle",
          x = 19.5266,
          y = 184.358,
          width = 0.363636,
          height = 0.363636,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 187,
          name = "greyTile20",
          type = "",
          shape = "rectangle",
          x = 19.7766,
          y = 168.608,
          width = 0.363636,
          height = 0.363636,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 188,
          name = "greyTile21",
          type = "",
          shape = "rectangle",
          x = 20.0266,
          y = 152.608,
          width = 0.363636,
          height = 0.363636,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 189,
          name = "greyTile22",
          type = "",
          shape = "rectangle",
          x = 20.5266,
          y = 136.358,
          width = 0.363636,
          height = 0.363636,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 194,
          name = "greyTile53",
          type = "",
          shape = "rectangle",
          x = 251.004,
          y = 216.367,
          width = 0.363636,
          height = 0.363636,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 195,
          name = "greyTile54",
          type = "",
          shape = "rectangle",
          x = 226.754,
          y = 217.413,
          width = 0.363636,
          height = 0.363636,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 196,
          name = "greyTile55",
          type = "",
          shape = "rectangle",
          x = 210.004,
          y = 217.89,
          width = 0.363636,
          height = 0.363636,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 197,
          name = "greyTile56",
          type = "",
          shape = "rectangle",
          x = 194.095,
          y = 217.367,
          width = 0.363636,
          height = 0.363636,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 198,
          name = "greyTile57",
          type = "",
          shape = "rectangle",
          x = 18.3106,
          y = 218.977,
          width = 0.363636,
          height = 0.363636,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 199,
          name = "greyTile58",
          type = "",
          shape = "rectangle",
          x = 19.9811,
          y = 199.864,
          width = 0.363636,
          height = 0.363636,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 16,
      name = "blueTile",
      visible = false,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {
        ["numObjects"] = 53
      },
      objects = {
        {
          id = 3,
          name = "blueTile1",
          type = "",
          shape = "rectangle",
          x = 137.178,
          y = 20.0358,
          width = 0.363636,
          height = 0.363636,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 83,
          name = "blueTile2",
          type = "",
          shape = "rectangle",
          x = 156.992,
          y = 19.253,
          width = 0.363636,
          height = 0.363636,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 84,
          name = "blueTile3",
          type = "",
          shape = "rectangle",
          x = 168.911,
          y = 19.2096,
          width = 0.363636,
          height = 0.363636,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 85,
          name = "blueTile4",
          type = "",
          shape = "rectangle",
          x = 188.725,
          y = 18.4268,
          width = 0.363636,
          height = 0.363636,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 86,
          name = "blueTile5",
          type = "",
          shape = "rectangle",
          x = 204.702,
          y = 18.4813,
          width = 0.363636,
          height = 0.363636,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 87,
          name = "blueTile6",
          type = "",
          shape = "rectangle",
          x = 216.621,
          y = 18.4379,
          width = 0.363636,
          height = 0.363636,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 88,
          name = "blueTile7",
          type = "",
          shape = "rectangle",
          x = 236.435,
          y = 17.6551,
          width = 0.363636,
          height = 0.363636,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 89,
          name = "blueTile23",
          type = "",
          shape = "rectangle",
          x = 122.27,
          y = 51.7086,
          width = 0.363636,
          height = 0.363636,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 90,
          name = "blueTile24",
          type = "",
          shape = "rectangle",
          x = 139.28,
          y = 51.3924,
          width = 0.363636,
          height = 0.363636,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 91,
          name = "blueTile25",
          type = "",
          shape = "rectangle",
          x = 155.821,
          y = 51.4278,
          width = 0.363636,
          height = 0.363636,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 92,
          name = "blueTile26",
          type = "",
          shape = "rectangle",
          x = 171.679,
          y = 51.2086,
          width = 0.363636,
          height = 0.363636,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 93,
          name = "blueTile27",
          type = "",
          shape = "rectangle",
          x = 188.234,
          y = 51.1652,
          width = 0.363636,
          height = 0.363636,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 94,
          name = "blueTile28",
          type = "",
          shape = "rectangle",
          x = 205.412,
          y = 51.0187,
          width = 0.363636,
          height = 0.363636,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 95,
          name = "blueTile41",
          type = "",
          shape = "rectangle",
          x = 121.452,
          y = 85.2313,
          width = 0.363636,
          height = 0.363636,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 96,
          name = "blueTile42",
          type = "",
          shape = "rectangle",
          x = 133.371,
          y = 85.1879,
          width = 0.363636,
          height = 0.363636,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 97,
          name = "blueTile44",
          type = "",
          shape = "rectangle",
          x = 169.435,
          y = 84.6551,
          width = 0.363636,
          height = 0.363636,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 98,
          name = "blueTile51",
          type = "",
          shape = "rectangle",
          x = 121.134,
          y = 124.606,
          width = 0.363636,
          height = 0.363636,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 99,
          name = "blueTile52",
          type = "",
          shape = "rectangle",
          x = 138.314,
          y = 124.677,
          width = 0.363636,
          height = 0.363636,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 100,
          name = "blueTile53",
          type = "",
          shape = "rectangle",
          x = 153.571,
          y = 125.121,
          width = 0.363636,
          height = 0.363636,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 101,
          name = "blueTile43",
          type = "",
          shape = "rectangle",
          x = 153.318,
          y = 84.3182,
          width = 0.363636,
          height = 0.363636,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 102,
          name = "blueTile50",
          type = "",
          shape = "rectangle",
          x = 83.0852,
          y = 132.256,
          width = 0.363636,
          height = 0.363636,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 103,
          name = "blueTile49",
          type = "",
          shape = "rectangle",
          x = 98.9318,
          y = 157.386,
          width = 0.363636,
          height = 0.363636,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 104,
          name = "blueTile48",
          type = "",
          shape = "rectangle",
          x = 115.659,
          y = 157.591,
          width = 0.363636,
          height = 0.363636,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 105,
          name = "blueTile47",
          type = "",
          shape = "rectangle",
          x = 131.636,
          y = 157.273,
          width = 0.363636,
          height = 0.363636,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 106,
          name = "blueTile45",
          type = "",
          shape = "rectangle",
          x = 187.568,
          y = 116.318,
          width = 0.363636,
          height = 0.363636,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 107,
          name = "blueTile46",
          type = "",
          shape = "rectangle",
          x = 188.568,
          y = 132.818,
          width = 0.363636,
          height = 0.363636,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 109,
          name = "blueTile29",
          type = "",
          shape = "rectangle",
          x = 220.818,
          y = 124.193,
          width = 0.363636,
          height = 0.363636,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 110,
          name = "blueTile30",
          type = "",
          shape = "rectangle",
          x = 220.568,
          y = 140.943,
          width = 0.363636,
          height = 0.363636,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 111,
          name = "blueTile31",
          type = "",
          shape = "rectangle",
          x = 220.818,
          y = 157.068,
          width = 0.363636,
          height = 0.363636,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 112,
          name = "blueTile32",
          type = "",
          shape = "rectangle",
          x = 220.818,
          y = 172.818,
          width = 0.363636,
          height = 0.363636,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 113,
          name = "blueTile8",
          type = "",
          shape = "rectangle",
          x = 251.568,
          y = 121.318,
          width = 0.363636,
          height = 0.363636,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 114,
          name = "blueTile9",
          type = "",
          shape = "rectangle",
          x = 251.318,
          y = 137.318,
          width = 0.363636,
          height = 0.363636,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 115,
          name = "blueTile10",
          type = "",
          shape = "rectangle",
          x = 251.068,
          y = 156.818,
          width = 0.363636,
          height = 0.363636,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 116,
          name = "blueTile11",
          type = "",
          shape = "rectangle",
          x = 252.568,
          y = 173.068,
          width = 0.363636,
          height = 0.363636,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 117,
          name = "blueTile12",
          type = "",
          shape = "rectangle",
          x = 252.068,
          y = 186.318,
          width = 0.363636,
          height = 0.363636,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 118,
          name = "blueTile13",
          type = "",
          shape = "rectangle",
          x = 252.318,
          y = 201.068,
          width = 0.363636,
          height = 0.363636,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 119,
          name = "blueTile33",
          type = "",
          shape = "rectangle",
          x = 135.568,
          y = 179.943,
          width = 0.363636,
          height = 0.363636,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 120,
          name = "blueTile34",
          type = "",
          shape = "rectangle",
          x = 115.818,
          y = 180.068,
          width = 0.363636,
          height = 0.363636,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 121,
          name = "blueTile35",
          type = "",
          shape = "rectangle",
          x = 100.443,
          y = 179.943,
          width = 0.363636,
          height = 0.363636,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 122,
          name = "blueTile36",
          type = "",
          shape = "rectangle",
          x = 84.0682,
          y = 179.318,
          width = 0.363636,
          height = 0.363636,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 123,
          name = "blueTile37",
          type = "",
          shape = "rectangle",
          x = 69.5682,
          y = 179.943,
          width = 0.363636,
          height = 0.363636,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 124,
          name = "blueTile14",
          type = "",
          shape = "rectangle",
          x = 100.318,
          y = 211.568,
          width = 0.363636,
          height = 0.363636,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 125,
          name = "blueTile15",
          type = "",
          shape = "rectangle",
          x = 83.3182,
          y = 211.318,
          width = 0.363636,
          height = 0.363636,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 126,
          name = "blueTile16",
          type = "",
          shape = "rectangle",
          x = 66.0682,
          y = 211.318,
          width = 0.363636,
          height = 0.363636,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 127,
          name = "blueTile17",
          type = "",
          shape = "rectangle",
          x = 55.3182,
          y = 212.568,
          width = 0.363636,
          height = 0.363636,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 128,
          name = "blueTile18",
          type = "",
          shape = "rectangle",
          x = 35.0682,
          y = 212.568,
          width = 0.363636,
          height = 0.363636,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 129,
          name = "blueTile38",
          type = "",
          shape = "rectangle",
          x = 50.9432,
          y = 133.693,
          width = 0.363636,
          height = 0.363636,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 131,
          name = "blueTile39",
          type = "",
          shape = "rectangle",
          x = 51.4432,
          y = 115.193,
          width = 0.363636,
          height = 0.363636,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 132,
          name = "blueTile40",
          type = "",
          shape = "rectangle",
          x = 51.1932,
          y = 99.1932,
          width = 0.363636,
          height = 0.363636,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 133,
          name = "blueTile19",
          type = "",
          shape = "rectangle",
          x = 19.5682,
          y = 117.318,
          width = 0.363636,
          height = 0.363636,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 134,
          name = "blueTile20",
          type = "",
          shape = "rectangle",
          x = 20.8182,
          y = 100.818,
          width = 0.363636,
          height = 0.363636,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 135,
          name = "blueTile21",
          type = "",
          shape = "rectangle",
          x = 20.3182,
          y = 85.5682,
          width = 0.363636,
          height = 0.363636,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 136,
          name = "blueTile22",
          type = "",
          shape = "rectangle",
          x = 21.8182,
          y = 71.0682,
          width = 0.363636,
          height = 0.363636,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 21,
      name = "fruit",
      visible = false,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {
        ["numObjects"] = 5
      },
      objects = {
        {
          id = 5,
          name = "fruit1",
          type = "",
          shape = "rectangle",
          x = 247.589,
          y = 25.657,
          width = 0.1875,
          height = 0.1875,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 8,
          name = "fruit2",
          type = "",
          shape = "rectangle",
          x = 19.3101,
          y = 220.576,
          width = 0.545455,
          height = 0.363636,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 11,
          name = "fruit3",
          type = "",
          shape = "rectangle",
          x = 220.295,
          y = 56.156,
          width = 0.363636,
          height = 0.545455,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 15,
          name = "fruit4",
          type = "",
          shape = "rectangle",
          x = 51.4937,
          y = 183.704,
          width = 0.909091,
          height = 0.545455,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 16,
          name = "fruit5",
          type = "",
          shape = "rectangle",
          x = 151.15,
          y = 124.964,
          width = 0.545455,
          height = 0.545455,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 27,
      name = "apple1",
      visible = true,
      opacity = 1,
      offsetx = 9.66667,
      offsety = -2.66667,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFo2AUjIJRMFLAd66BdsEoGAWjYLgDAHb2AQI="
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 28,
      name = "apple2",
      visible = true,
      opacity = 1,
      offsetx = 9.66667,
      offsety = -2.66667,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFo2AUjIJRMJLAd66BdsEoGAWjYDgDAHLyAQI="
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 29,
      name = "apple3",
      visible = true,
      opacity = 1,
      offsetx = 9.66667,
      offsety = -2.66667,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFo2AUjIJRMNLAd66BdsEoGAWjYLgCAG7uAQI="
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 30,
      name = "apple4",
      visible = true,
      opacity = 1,
      offsetx = 9.66667,
      offsety = -2.66667,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFo2AUjIJRMBLBd66BdsEoGAWjYDgCAGrqAQI="
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 31,
      name = "apple5",
      visible = true,
      opacity = 1,
      offsetx = 9.66667,
      offsety = -2.66667,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFo2AUjIJRMFLBd66BdsEoGAWjYLgBAGbmAQI="
    }
  }
}
