return {
  version = "1.2",
  luaversion = "5.1",
  tiledversion = "2020.01.22",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 39,
  height = 17,
  tilewidth = 16,
  tileheight = 16,
  nextlayerid = 44,
  nextobjectid = 43,
  properties = {},
  tilesets = {
    {
      name = "tilemap_packed",
      firstgid = 1,
      tilewidth = 16,
      tileheight = 16,
      spacing = 0,
      margin = 0,
      columns = 27,
      image = "../tileset/Tilemap/tilemap_packed.png",
      imagewidth = 432,
      imageheight = 288,
      objectalignment = "unspecified",
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 16,
        height = 16
      },
      properties = {},
      terrains = {},
      tilecount = 486,
      tiles = {}
    },
    {
      name = "test",
      firstgid = 487,
      tilewidth = 16,
      tileheight = 16,
      spacing = 0,
      margin = 0,
      columns = 27,
      image = "../tileset/Tilemap/test.png",
      imagewidth = 432,
      imageheight = 288,
      objectalignment = "unspecified",
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 16,
        height = 16
      },
      properties = {},
      terrains = {},
      tilecount = 486,
      tiles = {}
    },
    {
      name = "functionsTextTiles",
      firstgid = 973,
      tilewidth = 16,
      tileheight = 16,
      spacing = 0,
      margin = 0,
      columns = 30,
      image = "../graphics/functionsTextTiles.png",
      imagewidth = 480,
      imageheight = 480,
      objectalignment = "unspecified",
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 16,
        height = 16
      },
      properties = {},
      terrains = {},
      tilecount = 900,
      tiles = {}
    },
    {
      name = "UIpackSheet_transparent",
      firstgid = 1873,
      tilewidth = 16,
      tileheight = 16,
      spacing = 2,
      margin = 0,
      columns = 30,
      image = "../tileset/Tilemap/UIpackSheet_transparent.png",
      imagewidth = 538,
      imageheight = 592,
      objectalignment = "unspecified",
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 16,
        height = 16
      },
      properties = {},
      terrains = {},
      tilecount = 990,
      tiles = {}
    }
  },
  layers = {
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 32,
      name = "info",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {
        ["F0"] = 6,
        ["blueTile"] = true,
        ["door"] = true,
        ["face"] = "left",
        ["fruit"] = true,
        ["fruitsTotal"] = 2,
        ["grass"] = true,
        ["greyTile"] = false,
        ["numFunc"] = 1,
        ["totalSize"] = 6,
        ["yellowTile"] = true
      },
      encoding = "base64",
      compression = "zlib",
      data = "eJztwTEBAAAAwqD1T20JT6AAAOBjClwAAQ=="
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 17,
      name = "background",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFo2AUjALqAG2mgXbB0ASj4TYKBhIsYCZNfBSMAkIAANueAaE="
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 1,
      name = "grass",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJyTZWBgkCURy6HxZcgwA4aZmXBjcswbdRuqXcTaMeq2oeE2hkHsNhBtDsQWaFgOS35BdxslmFi3YQODJdwYgZgJDb9gHBxuA9nBhiVe0bHlALmNmLQ0UPl0qLgNW/oDYWY6uk0RaqcSmttw2TlQdf1gdhsxmF5uAwCCDz/s"
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 2,
      name = "street",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYCAPnGNkYDgPxBcYyTSAhmDUbeSBUbeRB0bdRh7YDHTTFiDeOgjdNpjDbdRtmGAb0L7pBPCVAXIbKEx2APFZPHjnALqNkJ0DFaejbiMPbCaiTKWH2wDouzv8"
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 4,
      name = "path",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFwxVoMw20C3AD14F2AB4w6jbywGB2GygvgNyHjgcDGCzuwAZwuW0wlC0wtw0Gt6CDwRyngzG8RsHwAwBTKwRj"
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 9,
      name = "house",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJzbysDAsAOIt0LpnQyDB8wB4rlIeN7AOgcFXALiy0j4ysA6ZxTQCQgBsTAUiwywW9CBLhDrQbH+ALsFGUxjZmDwANKeUOw1wO5BBhsHsdtAIBmIU6A4dYDdMlTAYUYGhiOMA+0K7OAe0F33oW47BqSPD1J3joJRQCkAAKWrFcQ="
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 10,
      name = "house_details",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJzLZWRgyAViEMhFYo8C/CCAEYItGBHsUTAKRsEoGAWjYBSMgpEOAFswAzY="
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 33,
      name = "close_door",
      visible = false,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFlABZxoF2wSgYBaNgFIyCUTAKRsHgAQAbsgAf"
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 5,
      name = "trees",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYMAE7Iy4MQcjFg10BEqMuLHyALttFIxsMGsQpr/ZjAwNIPrAwDoDKzjAAHHbKBgFo2DgwWCuUxWA7qgDYiMorTBI3AUCyWhu8RhEbhtIAADchAgF"
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 11,
      name = "extra",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYCANcDKSqIGG4B0Ug9wEw4MFsDJCMAsUDya3oQOWQey2UTAKRsEoGAW0BYqMEIwMXg2MU0bBMAEAZ+UDWA=="
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 12,
      name = "benches",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYCAdaKPxBcgwg1YA3W3o/IEEg8ltUUAcDcUxWNwykG6bAMQToXgSFrcMpNuyGVHxYHJbGyMqHkxuC2BExYPJbbpArAfF+ljcMtDhNheI5w1wuPEAsTMBrDFAbiPHnoFw22sgfoMFv8Wjh5YA2Z6XQPwKi5qXePTQEiDbw8kIoddB6VhGVHFsemgJkO1hYcSuBl18oOIUG6BXnAIAFc0fQQ=="
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 3,
      name = "cars",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYCAP3GWE0P2MZBpAB7BqELqtZxC6CQaWD2K3TRjEbls9iN02CigDRwdx3D4YBG7rArqhexC4AxtYCnTXskHqtlFAGAyXMn/iIPbHGhq6DQAOowsT"
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 20,
      name = "blueTile1",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFo2AUjIKRB84wD7QLRsEoGAWjYHgCAGM1ANA="
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 23,
      name = "yellowTile1",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFo2AUjILhDU4xD7QLRsEoGAWjYOQAAGh5AM4="
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 21,
      name = "blueTile2",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFo2AUjIJRMApGwUgAZ5gH2gWjYCQAAPyAANA="
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 22,
      name = "blueTile3",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFwxWcYR5oF4yCUTAKRsEoGAWjYKQBAOozANA="
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 24,
      name = "fruit1",
      visible = true,
      opacity = 1,
      offsetx = 0.25,
      offsety = -3.5,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFo2AUjIJRMApGwUgAN9kG2gWjYCQAACMMAOA="
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 25,
      name = "fruit2",
      visible = true,
      opacity = 1,
      offsetx = 0.5,
      offsety = -3.5,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFwxXcZBtoF4yCUTAKBgMwH8RlwajbRsEoGH4AADHCAZc="
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 13,
      name = "end",
      visible = false,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      objects = {
        {
          id = 1,
          name = "end",
          type = "",
          shape = "rectangle",
          x = 32,
          y = 32,
          width = 16,
          height = 20.0114,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 19,
      name = "fruit",
      visible = false,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {
        ["numObjects"] = 2
      },
      objects = {
        {
          id = 38,
          name = "fruit1",
          type = "",
          shape = "rectangle",
          x = 38.9375,
          y = 219,
          width = 0.53125,
          height = 0.4375,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 41,
          name = "fruit2",
          type = "",
          shape = "rectangle",
          x = 39.25,
          y = 59.625,
          width = 0.152778,
          height = 0.152778,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 15,
      name = "yellowTile",
      visible = false,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {
        ["numObjects"] = 1
      },
      objects = {
        {
          id = 17,
          name = "yellowTile1",
          type = "",
          shape = "rectangle",
          x = 34.0889,
          y = 135.078,
          width = 0.486868,
          height = 0.886868,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 16,
      name = "blueTile",
      visible = false,
      opacity = 0.88,
      offsetx = 0,
      offsety = 0,
      properties = {
        ["numObjects"] = 3
      },
      objects = {
        {
          id = 34,
          name = "blueTile2",
          type = "",
          shape = "rectangle",
          x = 38.7273,
          y = 218,
          width = 0.306061,
          height = 0.443434,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 35,
          name = "blueTile3",
          type = "",
          shape = "rectangle",
          x = 39.8717,
          y = 55.5343,
          width = 0.525253,
          height = 0.643434,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 36,
          name = "blueTile1",
          type = "",
          shape = "rectangle",
          x = 118.727,
          y = 135.818,
          width = 1.27273,
          height = 2,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 14,
      name = "grass",
      visible = false,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {
        ["numObjects"] = 5
      },
      objects = {
        {
          id = 2,
          name = "grass1",
          type = "",
          shape = "rectangle",
          x = 1.19697,
          y = 3.66667,
          width = 26.5,
          height = 266.5,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 3,
          name = "grass2",
          type = "",
          shape = "rectangle",
          x = 51.8182,
          y = 0.181818,
          width = 234.5,
          height = 122.5,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 4,
          name = "grass3",
          type = "",
          shape = "rectangle",
          x = 51.4848,
          y = 148,
          width = 235,
          height = 122,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 5,
          name = "grass5",
          type = "",
          shape = "rectangle",
          x = 0.5,
          y = 227.5,
          width = 254,
          height = 43.5,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 10,
          name = "grass4",
          type = "",
          shape = "rectangle",
          x = 131.333,
          y = -0.666667,
          width = 160,
          height = 256,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 18,
      name = "player",
      visible = false,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      objects = {
        {
          id = 19,
          name = "player",
          type = "",
          shape = "rectangle",
          x = 112,
          y = 128,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 26,
      name = "text",
      visible = true,
      opacity = 1,
      offsetx = -31.5,
      offsety = -25.5,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJzt0kkOgkAURdGf0OxIBBtgD2KzDXvW434EdSoJ61DUeIdMalpA8m9ykprVS6VEtL70dEUqjDyRAGOEiDDBFDPMESNB6tnZtuCeDEussMYGL/a+0eCDr2tnT7stO3bY44AjTjgjt/Q+pq6OSIESN9ROt3va3Xu0xdTF50/h55vPtnsM4N00TdO67A+daB1+"
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 34,
      name = "buttonsSecondRow",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {
        ["blue"] = "blueTile",
        ["yellow"] = "yellowTile"
      },
      encoding = "base64",
      compression = "zlib",
      data = "eJztwTEBAAAAwqD1T20JT6AAAOBjClwAAQ=="
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 35,
      name = "buttonsThirdRow",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {
        ["paint"] = "paint grey"
      },
      encoding = "base64",
      compression = "zlib",
      data = "eJztwTEBAAAAwqD1T20JT6AAAOBjClwAAQ=="
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 31,
      name = "text4",
      visible = false,
      opacity = 1,
      offsetx = -32,
      offsety = -14,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJztwTEBAAAAwqD1T20JT6AAAOBjClwAAQ=="
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 28,
      name = "answer",
      visible = false,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {
        ["size"] = 6
      },
      objects = {
        {
          id = 23,
          name = "answer3",
          type = "",
          shape = "rectangle",
          x = 384.391,
          y = 86.42,
          width = 17,
          height = 17,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 25,
          name = "answer1",
          type = "",
          shape = "rectangle",
          x = 336.458,
          y = 86.4895,
          width = 17,
          height = 17,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 27,
          name = "answer2",
          type = "",
          shape = "rectangle",
          x = 360.333,
          y = 86.4163,
          width = 17,
          height = 17,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 28,
          name = "answer4",
          type = "",
          shape = "rectangle",
          x = 408.339,
          y = 86.3529,
          width = 17,
          height = 17,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 29,
          name = "answer5",
          type = "",
          shape = "rectangle",
          x = 432.429,
          y = 86.4453,
          width = 17,
          height = 17,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 30,
          name = "answer6",
          type = "",
          shape = "rectangle",
          x = 456.375,
          y = 86.417,
          width = 17,
          height = 17,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 40,
      name = "buttons",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFo2AUjIJRMAoGHpRxMjCUo+EKzoF2FQRMAbpjKhqeNuo2gmDUbeSBTUB3bEbDWwaJ24gBAIwRFjk="
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 41,
      name = "fruitBanner",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFo2AUjIJRQE3wj4OB4T8aZuAcaFdBgAzQHbJoWG6QuG0UjIJRMDwAALEsBhA="
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 42,
      name = "apple2",
      visible = true,
      opacity = 1,
      offsetx = 0.5,
      offsety = -3.5,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFo2AUjIJRMBLBTbaBdsEoGAWjYDgCANanAOA="
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 43,
      name = "apple1",
      visible = true,
      opacity = 1,
      offsetx = 0.5,
      offsety = -3.5,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFo2AUjIJRMNLATbaBdsEoGAWjYLgCANojAOA="
    }
  }
}
