return {
  version = "1.2",
  luaversion = "5.1",
  tiledversion = "2020.01.22",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 39,
  height = 17,
  tilewidth = 16,
  tileheight = 16,
  nextlayerid = 87,
  nextobjectid = 76,
  properties = {},
  tilesets = {
    {
      name = "functionsTextTiles",
      firstgid = 1,
      tilewidth = 16,
      tileheight = 16,
      spacing = 0,
      margin = 0,
      columns = 30,
      image = "../graphics/functionsTextTiles.png",
      imagewidth = 480,
      imageheight = 480,
      objectalignment = "unspecified",
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 16,
        height = 16
      },
      properties = {},
      terrains = {},
      tilecount = 900,
      tiles = {}
    },
    {
      name = "test",
      firstgid = 901,
      tilewidth = 16,
      tileheight = 16,
      spacing = 0,
      margin = 0,
      columns = 27,
      image = "../tileset/Tilemap/test.png",
      imagewidth = 432,
      imageheight = 288,
      objectalignment = "unspecified",
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 16,
        height = 16
      },
      properties = {},
      terrains = {},
      tilecount = 486,
      tiles = {}
    },
    {
      name = "UIpackSheet_transparent",
      firstgid = 1387,
      tilewidth = 16,
      tileheight = 16,
      spacing = 2,
      margin = 0,
      columns = 30,
      image = "../tileset/Tilemap/UIpackSheet_transparent.png",
      imagewidth = 538,
      imageheight = 592,
      objectalignment = "unspecified",
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 16,
        height = 16
      },
      properties = {},
      terrains = {},
      tilecount = 990,
      tiles = {}
    }
  },
  layers = {
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 14,
      name = "info",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {
        ["F0"] = 3,
        ["F1"] = 0,
        ["blueTile"] = true,
        ["door"] = false,
        ["face"] = "right",
        ["fruit"] = true,
        ["fruitsTotal"] = 20,
        ["grass"] = true,
        ["greyTile"] = false,
        ["numFunc"] = 1,
        ["totalSize"] = 3,
        ["yellowTile"] = true
      },
      encoding = "base64",
      compression = "zlib",
      data = "eJztwTEBAAAAwqD1T20JT6AAAOBjClwAAQ=="
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 1,
      name = "background",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxbyczAsJIEvAqNv5CGmBR3jbptaLjtCIn46CAON3Q86rbB57Y+EnE/Hd2GntYnA/EkLOIwuYEsQ1ZgsR+EQQCb3KjbRt1GDbfBwGBz21pm7OXHukHgNnxlLT3dBgC+EazR"
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 3,
      name = "path",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFo2AUjIJRMAoIgwxWTDxYAMgtWayo9GABGWjuGmxuG+zhNhjT2yjADwBDBAqw"
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 8,
      name = "houses",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJzbwMzAsAkNbwBiGJBlYWCQA2J5IDZnYaArOA10x1k0DBJjZmVgYAFiC6B7LIHYCoiD6Oy2Z0B3vEDDz5DCLRjonhAgDqWzu0bBKBgFo4BScA9Ylt0H4gfMhNXSG/wEuukXEP8ehG4TAZb3okAsNgjL/enMEDxjEIYbrO2xGYgZWQfaNagA1vY4NwjDDdltgy3cAOsmICE="
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 4,
      name = "fruits",
      visible = false,
      opacity = 1,
      offsetx = 16.3333,
      offsety = -3.16667,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFo2AUjIJRMArwA15mBoZ0ZlR6sIB0Zuz0YACw8AKB0XAjHgzm9DYKCAMAG5AFeQ=="
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 7,
      name = "streets",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYCAdBLEyMAQDcQgrGZppDEbdRh4YzG4zB7rJAogtaew2aVbSsBQQR9Ap3MxYScOmUFqGDm4LZCUNBwCx7Wh6IwsM5nw66jbywKjbyAOjbiMP0MttAINDGX8="
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 11,
      name = "cars",
      visible = true,
      opacity = 1,
      offsetx = -8.5,
      offsety = 6,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBh+wI11oF2AGyQOYrfRA/AB/c8/SMNAE+guLRxucwGKu0LlvIC09yDyQzzQLQmDyD3DBYgO4jA1GMRuGwWjgF5AeBDnA71B7DZ6AADWfwPL"
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 9,
      name = "details",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJy7wsKAAa5gEcMnTisAsu8akp0gNrIbVFkReN4AuI0XaK8iECuxQtjIbmsBshexQGgYkGdlaKCvK4kHLiyD122jgDSgPYjj0g3NbXKsA+QQIoALjcuUPDqXWaSAJUC3MQ3SuHk+iMNtFIyCUQABAKOOEEA="
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 10,
      name = "details2",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYKAMrGem0AAiwBUWCMYHLmKRp4fb0MFMqDvOAulzQHweh7sHwm3EglG3kQdG3UYeoKXbZhAoNwiBkRpuIGBPQdiN5HCjBIy6jTww6jbyAC3dBgByDxJK"
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 12,
      name = "people",
      visible = true,
      opacity = 1,
      offsetx = 0.5,
      offsety = -7,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFwxH8ZiFOnS8rbd0xCkbBUAQcROafUTAKRsEoGAWYAABzGAFe"
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 6,
      name = "player",
      visible = false,
      opacity = 1,
      offsetx = 0,
      offsety = -7,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFo2AUjIJRMApGAa3BfOaBdsEoGAX0AQDjwACj"
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 16,
      name = "buttons",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJzt08cNAjEQRuHR7sGwSxukbYPYBrENYgGwhQB9ENsg1sBD5mRx4OY5+Je++5PGFgkLCwv7vZURWTty47vKbkPH1rFT0laORdqOLPZdZbePRA444oQzLpHvKrsrHTfc8cATLyVthvsVUESCFCUlN/28twqqqKGu6L016Gii9f0HHXSVtPXo6GOAIUYYK2mb0DHFDHMssFTS9s/ei+EcOw=="
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 39,
      name = "fruit1",
      visible = true,
      opacity = 1,
      offsetx = 0.5625,
      offsety = -2.625,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFo2AUjIJRMApGwSgYXICXeaBdMArIBQAmGQAR"
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 40,
      name = "fruit2",
      visible = true,
      opacity = 1,
      offsetx = 0.5625,
      offsety = -2.625,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFo2AUjIJRMApGwSgYfCCdeaBdMArIAQDAiQBr"
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 41,
      name = "fruit3",
      visible = true,
      opacity = 1,
      offsetx = 0.5625,
      offsety = -2.625,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFo2AUjIJRMApGwSgYnICXeaBdMApIBQAlmQAR"
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 42,
      name = "fruit4",
      visible = true,
      opacity = 1,
      offsetx = 0.5625,
      offsety = -2.625,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFo2AUjIJRMApGwSgYvCCdeaBdMApIAQC9OQBr"
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 43,
      name = "fruit5",
      visible = true,
      opacity = 1,
      offsetx = 0.5625,
      offsety = -2.625,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFo2AUjIJRMApGwSgY3ICXeaBdMAqIBQAlGQAR"
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 44,
      name = "fruit6",
      visible = true,
      opacity = 1,
      offsetx = 0.5625,
      offsety = -2.625,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFo2AUjIJRMApGwShgYEhnHmgXjILhAAD8KQBr"
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 45,
      name = "fruit7",
      visible = true,
      opacity = 1,
      offsetx = 0.5625,
      offsety = -2.625,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFo2AUjIJRMApGwUgG6cwD7YJRMJwAAP95AGs="
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 46,
      name = "fruit8",
      visible = true,
      opacity = 1,
      offsetx = 0.5625,
      offsety = -2.625,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFo2AUjIJRMApGwUgE6cwD7YJRMBwBAALYAGs="
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 47,
      name = "fruit9",
      visible = true,
      opacity = 1,
      offsetx = 0.5625,
      offsety = -2.625,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFo2AUjIJRMApGAa0AL/NAu2AUjAL6AgA5mQAR"
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 48,
      name = "fruit10",
      visible = true,
      opacity = 1,
      offsetx = 0.5625,
      offsety = -2.625,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFo2AUjIJRMApGAS1BOvNAu2AUjAL6AQBByABr"
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 49,
      name = "fruit11",
      visible = true,
      opacity = 1,
      offsetx = 0.5625,
      offsety = -2.625,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFo2AUjIJRMApGAT1AOvNAu2AUjALaAwA+eABr"
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 50,
      name = "fruit12",
      visible = true,
      opacity = 1,
      offsetx = 0.5625,
      offsety = -2.625,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFo2AUjIJRMApGAb0AL/NAu2AUjALaAgA4mQAR"
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 51,
      name = "fruit13",
      visible = true,
      opacity = 1,
      offsetx = 0.5625,
      offsety = -2.625,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFo2AUjIJRMAqGF0hnHmgXjIJRMHIBAH1oAGs="
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 52,
      name = "fruit14",
      visible = true,
      opacity = 1,
      offsetx = 0.5625,
      offsety = -2.625,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFo2AUjIJRMAqGB+BlHmgXjIJRMAoAQtkAEQ=="
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 53,
      name = "fruit15",
      visible = true,
      opacity = 1,
      offsetx = 0.5625,
      offsety = -2.625,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFo2AUjIJRMAqGNkhnHmgXjIJRMApgAACECABr"
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 54,
      name = "fruit16",
      visible = true,
      opacity = 1,
      offsetx = 0.5625,
      offsety = -2.625,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFo2AUjIJRMAoIg3TmgXbBKBgFo2AoAADEoABr"
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 55,
      name = "fruit17",
      visible = true,
      opacity = 1,
      offsetx = 0.5625,
      offsety = -2.625,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFo2AUjIJRMAqIA7zMA+2CUTAKRsFgBwBM2QAR"
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 56,
      name = "fruit18",
      visible = true,
      opacity = 1,
      offsetx = 0.5625,
      offsety = -2.625,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFo2AUjIJRMAqIB+nMA+2CUTAKRsFgBgDBUABr"
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 57,
      name = "fruit19",
      visible = true,
      opacity = 1,
      offsetx = 0.5625,
      offsety = -2.625,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFo2AUjIJRMApIA7zMA+2CUTAKRsFgBQBMWQAR"
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 58,
      name = "fruit20",
      visible = true,
      opacity = 1,
      offsetx = 0.5625,
      offsety = -2.625,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFo2AUjIJRMApIB+nMA+2CUTAKRsFgBAC+AABr"
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 59,
      name = "apple1",
      visible = true,
      opacity = 1,
      offsetx = -0.5,
      offsety = -3.25,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFo2AUjIJRMFIAL/NAu2AUjIJRMNwBAFDZABE="
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 60,
      name = "apple2",
      visible = true,
      opacity = 1,
      offsetx = -0.5,
      offsety = -3.25,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFo2AUjIJRMJIAL/NAu2AUjIJRMJwBAFCZABE="
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 61,
      name = "apple3",
      visible = true,
      opacity = 1,
      offsetx = -0.5,
      offsety = -3.25,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFo2AUjIJRMNIAL/NAu2AUjIJRMFwBAFBZABE="
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 62,
      name = "apple4",
      visible = true,
      opacity = 1,
      offsetx = -0.5,
      offsety = -3.25,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFo2AUjIJRMBIBL/NAu2AUjIJRMBwBAFAZABE="
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 63,
      name = "apple5",
      visible = true,
      opacity = 1,
      offsetx = -0.5,
      offsety = -3.25,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFo2AUjIJRMFIBL/NAu2AUjIJRMNwAAE/ZABE="
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 64,
      name = "apple6",
      visible = true,
      opacity = 1,
      offsetx = -0.5,
      offsety = -3.25,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFo2AUjIJRMJIBL/NAu2AUjIJRMJwAAE+ZABE="
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 65,
      name = "apple7",
      visible = true,
      opacity = 1,
      offsetx = 0.75,
      offsety = -2,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFo2AUjIJRQE3AyzzQLhgFo2AUjIKBAwBamQAR"
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 66,
      name = "apple8",
      visible = true,
      opacity = 1,
      offsetx = 0.75,
      offsety = -2,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFo2AUjIJRQG3AyzzQLhgFo2AUjIKBAQBaWQAR"
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 67,
      name = "apple9",
      visible = true,
      opacity = 1,
      offsetx = 0.75,
      offsety = -2,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFo2AUjIJRQAvAyzzQLhgFo2AUjAL6AwBaGQAR"
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 68,
      name = "apple10",
      visible = true,
      opacity = 1,
      offsetx = 0.75,
      offsety = -2,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFo2AUjIJRQCvAyzzQLhgFo2AUjAL6AgBZ2QAR"
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 69,
      name = "apple11",
      visible = true,
      opacity = 1,
      offsetx = 0.75,
      offsety = -2,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFo2AUjIJRQEvAyzzQLhgFo2AUjAL6AQBZmQAR"
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 70,
      name = "apple12",
      visible = true,
      opacity = 1,
      offsetx = 0.75,
      offsety = -2,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFo2AUjIJRQGvAyzzQLhgFo2AUjAL6AABZWQAR"
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 71,
      name = "apple13",
      visible = true,
      opacity = 1,
      offsetx = 1,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFo2AUjIKhB3iZB9oFo2AUjIJRMAqwAQBkWQAR"
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 72,
      name = "apple14",
      visible = true,
      opacity = 1,
      offsetx = 1,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFo2AUjIKhCXiZB9oFo2AUjIJRMArQAQBkGQAR"
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 73,
      name = "apple15",
      visible = true,
      opacity = 1,
      offsetx = 1,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFo2AUjIKhC3iZB9oFo2AUjIJRMAqQAQBj2QAR"
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 74,
      name = "apple16",
      visible = true,
      opacity = 1,
      offsetx = 1,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFo2AUjIKhDXiZB9oFo2AUjIJRMApgAABjmQAR"
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 83,
      name = "buttonsSecondRow",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {
        ["blue"] = "blueTile",
        ["yellow"] = "yellowTile"
      },
      encoding = "base64",
      compression = "zlib",
      data = "eJztwTEBAAAAwqD1T20JT6AAAOBjClwAAQ=="
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 84,
      name = "buttonsThirdRow",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJztwTEBAAAAwqD1T20JT6AAAOBjClwAAQ=="
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 75,
      name = "apple17",
      visible = true,
      opacity = 1,
      offsetx = 1,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFo2AUjIKhD3iZB9oFo2AUjIJRMApAAABjWQAR"
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 76,
      name = "apple18",
      visible = true,
      opacity = 1,
      offsetx = 1,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFo2AUjILhAXiZB9oFo2AUjIJRMAoAYxkAEQ=="
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 77,
      name = "apple19",
      visible = true,
      opacity = 1,
      offsetx = 1.5,
      offsety = 2.25,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFo2AUjAL8gJd5oF0wCkbBKBgFo2CoAABtmQAR"
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 78,
      name = "apple20",
      visible = true,
      opacity = 1,
      offsetx = 1.5,
      offsety = 2.25,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFo2AUjALCgJd5oF0wCkbBKBgFo2AoAABtWQAR"
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 79,
      name = "text",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJzt0MkNgDAMBVGHAA1QCXTFFtYOoEbqYRAnbtwcRR7pST5+WST9WifSoceAEQETZixYsWF32mvj6XlFBo8cle6cT4X2gB9dPK/meY1/7xgqtQdYVmQdOLVHWFZi3WB2CIM="
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 81,
      name = "grass",
      visible = false,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {
        ["numObjects"] = 4
      },
      objects = {
        {
          id = 31,
          name = "grass1",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 248.75,
          width = 304,
          height = 23.25,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 33,
          name = "grass2",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 0,
          width = 86.1667,
          height = 272,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 34,
          name = "grass3",
          type = "",
          shape = "rectangle",
          x = 4.66667,
          y = 1,
          width = 304,
          height = 150.75,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 35,
          name = "grass4",
          type = "",
          shape = "rectangle",
          x = 183.667,
          y = 0,
          width = 120.333,
          height = 272,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 82,
      name = "blueTile",
      visible = false,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {
        ["numObjects"] = 5
      },
      objects = {
        {
          id = 36,
          name = "blueTile1",
          type = "",
          shape = "rectangle",
          x = 120.125,
          y = 183,
          width = 0.25,
          height = 0.25,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 38,
          name = "blueTile2",
          type = "",
          shape = "rectangle",
          x = 151.636,
          y = 182.727,
          width = 0.363636,
          height = 0.363636,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 39,
          name = "blueTile3",
          type = "",
          shape = "rectangle",
          x = 135.909,
          y = 199.091,
          width = 0.363636,
          height = 0.3,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 40,
          name = "blueTile4",
          type = "",
          shape = "rectangle",
          x = 119.455,
          y = 215.455,
          width = 0.272727,
          height = 0.0909091,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 41,
          name = "blueTile5",
          type = "",
          shape = "rectangle",
          x = 152.182,
          y = 215.182,
          width = 0.181818,
          height = 0.363636,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 13,
      name = "player",
      visible = false,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      objects = {
        {
          id = 42,
          name = "player",
          type = "",
          shape = "rectangle",
          x = 128,
          y = 192,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 17,
      name = "fruit",
      visible = false,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {
        ["numObjects"] = 20
      },
      objects = {
        {
          id = 2,
          name = "fruit1",
          type = "",
          shape = "rectangle",
          x = 103.091,
          y = 231.636,
          width = 0.3,
          height = 0.3,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 3,
          name = "fruit2",
          type = "",
          shape = "rectangle",
          x = 119.818,
          y = 231.818,
          width = 0.3,
          height = 0.3,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 4,
          name = "fruit3",
          type = "",
          shape = "rectangle",
          x = 135.818,
          y = 231.374,
          width = 0.3,
          height = 0.3,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 5,
          name = "fruit4",
          type = "",
          shape = "rectangle",
          x = 151.636,
          y = 231.455,
          width = 0.3,
          height = 0.3,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 7,
          name = "fruit5",
          type = "",
          shape = "rectangle",
          x = 167.818,
          y = 230.727,
          width = 0.3,
          height = 0.3,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 8,
          name = "fruit6",
          type = "",
          shape = "rectangle",
          x = 167.636,
          y = 215.818,
          width = 0.3,
          height = 0.3,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 9,
          name = "fruit7",
          type = "",
          shape = "rectangle",
          x = 136,
          y = 215.636,
          width = 0.3,
          height = 0.3,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 10,
          name = "fruit8",
          type = "",
          shape = "rectangle",
          x = 104.182,
          y = 215.273,
          width = 0.3,
          height = 0.3,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 11,
          name = "fruit9",
          type = "",
          shape = "rectangle",
          x = 103.818,
          y = 199.455,
          width = 0.545455,
          height = 0.363636,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 12,
          name = "fruit10",
          type = "",
          shape = "rectangle",
          x = 119.818,
          y = 199.273,
          width = 0.27,
          height = 0.3,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 13,
          name = "fruit11",
          type = "",
          shape = "rectangle",
          x = 151.455,
          y = 198.909,
          width = 0.3,
          height = 0.3,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 14,
          name = "fruit12",
          type = "",
          shape = "rectangle",
          x = 167.818,
          y = 199.455,
          width = 0.3,
          height = 0.3,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 15,
          name = "fruit13",
          type = "",
          shape = "rectangle",
          x = 168,
          y = 183.818,
          width = 0.181818,
          height = 0.181818,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 16,
          name = "fruit14",
          type = "",
          shape = "rectangle",
          x = 135.455,
          y = 183.273,
          width = 0.545455,
          height = 0.26087,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 18,
          name = "fruit15",
          type = "",
          shape = "rectangle",
          x = 103.818,
          y = 183.091,
          width = 0.363636,
          height = 0.545455,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 19,
          name = "fruit16",
          type = "",
          shape = "rectangle",
          x = 103.818,
          y = 167.091,
          width = 0.3,
          height = 0.3,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 20,
          name = "fruit17",
          type = "",
          shape = "rectangle",
          x = 119.636,
          y = 167.091,
          width = 0.545455,
          height = 0.363636,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 22,
          name = "fruit18",
          type = "",
          shape = "rectangle",
          x = 135.455,
          y = 167.091,
          width = 0.181818,
          height = 0.181818,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 24,
          name = "fruit19",
          type = "",
          shape = "rectangle",
          x = 151.455,
          y = 167.091,
          width = 0.363636,
          height = 0.181818,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 25,
          name = "fruit20",
          type = "",
          shape = "rectangle",
          x = 168,
          y = 167.091,
          width = 0.363636,
          height = 0.545455,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 85,
      name = "yellowTile",
      visible = false,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {
        ["numObjects"] = 20
      },
      objects = {
        {
          id = 43,
          name = "yellowTile1",
          type = "",
          shape = "rectangle",
          x = 103.455,
          y = 231.636,
          width = 0.3,
          height = 0.3,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 44,
          name = "yellowTile2",
          type = "",
          shape = "rectangle",
          x = 119.636,
          y = 231.455,
          width = 0.3,
          height = 0.3,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 47,
          name = "yellowTile3",
          type = "",
          shape = "rectangle",
          x = 135.909,
          y = 231.909,
          width = 0.3,
          height = 0.3,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 48,
          name = "yellowTile4",
          type = "",
          shape = "rectangle",
          x = 153,
          y = 231.455,
          width = 0.3,
          height = 0.3,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 49,
          name = "yellowTile5",
          type = "",
          shape = "rectangle",
          x = 167.818,
          y = 231.273,
          width = 0.3,
          height = 0.3,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 50,
          name = "yellowTile6",
          type = "",
          shape = "rectangle",
          x = 103.636,
          y = 215.273,
          width = 0.3,
          height = 0.3,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 51,
          name = "yellowTile7",
          type = "",
          shape = "rectangle",
          x = 135.455,
          y = 215.455,
          width = 0.3,
          height = 0.3,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 52,
          name = "yellowTile8",
          type = "",
          shape = "rectangle",
          x = 170.545,
          y = 215.455,
          width = 0.3,
          height = 0.3,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 54,
          name = "yellowTile9",
          type = "",
          shape = "rectangle",
          x = 103.091,
          y = 198.727,
          width = 0.3,
          height = 0.3,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 55,
          name = "yellowTile10",
          type = "",
          shape = "rectangle",
          x = 120,
          y = 198.727,
          width = 0.3,
          height = 0.3,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 61,
          name = "yellowTile11",
          type = "",
          shape = "rectangle",
          x = 151.818,
          y = 198.727,
          width = 0.3,
          height = 0.3,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 62,
          name = "yellowTile20",
          type = "",
          shape = "rectangle",
          x = 168.727,
          y = 166.182,
          width = 0.3,
          height = 0.3,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 63,
          name = "yellowTile12",
          type = "",
          shape = "rectangle",
          x = 168.182,
          y = 199.636,
          width = 0.3,
          height = 0.3,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 64,
          name = "yellowTile13",
          type = "",
          shape = "rectangle",
          x = 104.545,
          y = 183.273,
          width = 0.3,
          height = 0.3,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 65,
          name = "yellowTile14",
          type = "",
          shape = "rectangle",
          x = 136,
          y = 183.455,
          width = 0.3,
          height = 0.3,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 70,
          name = "yellowTile15",
          type = "",
          shape = "rectangle",
          x = 169.455,
          y = 183.455,
          width = 0.3,
          height = 0.3,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 71,
          name = "yellowTile16",
          type = "",
          shape = "rectangle",
          x = 105.455,
          y = 166.364,
          width = 0.3,
          height = 0.3,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 72,
          name = "yellowTile17",
          type = "",
          shape = "rectangle",
          x = 118.909,
          y = 167.455,
          width = 0.3,
          height = 0.3,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 73,
          name = "yellowTile18",
          type = "",
          shape = "rectangle",
          x = 136.727,
          y = 167.273,
          width = 0.3,
          height = 0.3,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 75,
          name = "yellowTile19",
          type = "",
          shape = "rectangle",
          x = 152,
          y = 166.909,
          width = 0.3,
          height = 0.3,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 80,
      name = "answer",
      visible = false,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {
        ["numObjects"] = 3
      },
      objects = {
        {
          id = 27,
          name = "answer1",
          type = "",
          shape = "rectangle",
          x = 320,
          y = 80,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 28,
          name = "answer2",
          type = "",
          shape = "rectangle",
          x = 344.063,
          y = 79.9375,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 29,
          name = "answer3",
          type = "",
          shape = "rectangle",
          x = 367.989,
          y = 80.0056,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    }
  }
}
