return {
  version = "1.2",
  luaversion = "5.1",
  tiledversion = "2020.01.22",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 39,
  height = 17,
  tilewidth = 16,
  tileheight = 16,
  nextlayerid = 38,
  nextobjectid = 39,
  properties = {},
  tilesets = {
    {
      name = "UIpackSheet_transparent",
      firstgid = 1,
      tilewidth = 16,
      tileheight = 16,
      spacing = 2,
      margin = 0,
      columns = 30,
      image = "../tileset/Tilemap/UIpackSheet_transparent.png",
      imagewidth = 538,
      imageheight = 592,
      objectalignment = "unspecified",
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 16,
        height = 16
      },
      properties = {},
      terrains = {},
      tilecount = 990,
      tiles = {}
    },
    {
      name = "roguelikeCity",
      firstgid = 991,
      tilewidth = 16,
      tileheight = 16,
      spacing = 1,
      margin = 0,
      columns = 37,
      image = "../tileset/Tilemap/roguelikeCity.png",
      imagewidth = 628,
      imageheight = 475,
      objectalignment = "unspecified",
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 16,
        height = 16
      },
      properties = {},
      terrains = {},
      tilecount = 1036,
      tiles = {}
    },
    {
      name = "functionsTextTiles",
      firstgid = 2027,
      tilewidth = 16,
      tileheight = 16,
      spacing = 0,
      margin = 0,
      columns = 30,
      image = "../graphics/functionsTextTiles.png",
      imagewidth = 480,
      imageheight = 480,
      objectalignment = "unspecified",
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 16,
        height = 16
      },
      properties = {},
      terrains = {},
      tilecount = 900,
      tiles = {}
    },
    {
      name = "test",
      firstgid = 2927,
      tilewidth = 16,
      tileheight = 16,
      spacing = 0,
      margin = 0,
      columns = 27,
      image = "../tileset/Tilemap/test.png",
      imagewidth = 432,
      imageheight = 288,
      objectalignment = "unspecified",
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 16,
        height = 16
      },
      properties = {},
      terrains = {},
      tilecount = 486,
      tiles = {}
    }
  },
  layers = {
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 14,
      name = "info",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {
        ["F0"] = 3,
        ["F1"] = 4,
        ["blueTile"] = true,
        ["door"] = false,
        ["face"] = "right",
        ["fruit"] = true,
        ["fruitsTotal"] = 5,
        ["grass"] = true,
        ["greyTile"] = false,
        ["numFunc"] = 2,
        ["totalSize"] = 7,
        ["yellowTile"] = true
      },
      encoding = "base64",
      compression = "zlib",
      data = "eJztwTEBAAAAwqD1T20JT6AAAOBjClwAAQ=="
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 1,
      name = "background",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJw7xcbAcIoE/AGIbXgZGGyB2A6II9gZGBYBcQ0Q11IZk+IubG6DiS9ipz4edRt5eD4bYTwYwm0wu22wxelQc9tpNki5BcMiUAwSl2Yf+HBbigXD5AbabaTG6WDA2OosXOFGrh3UCrcIAvGCLW0Qi2nttoFMb6Nuo8xtx4D4OJUxAIJfxq4="
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 6,
      name = "city1",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYKAMRLDTDlMKYOYsooJZ1AaLRt1GFhh1G3lg1G2YdmLD2NQM9nAbjGUvyG1eLLTB1HDbKTYIxgZgcugYFyBGDbXcRi4YdRt5gBrmEZuOyDGXGmbQym0AIz1Fmw=="
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 3,
      name = "house1",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFo2AUjIJRMApGHnjPzMDwEQl/YB5oFyHAJ6BbvjIzLIBhcRYGhl+sDAw/sWBsACb3B4c8JUAE6BYxJCzKQp45imzUdRcIzAS6ZRYSng3EW9gRuId9cLkNGWxAcicusIUINbRwG7EAFm4AtHUk5A=="
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 4,
      name = "house1details",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 5.33333,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFo2AUjIJRMApGAQwUsNJGLTXAVCT7CNk9lc5uAwGYmwjZfZOddm7wYkOlYYCU8KBnvJIaFrSKV1zhRg4AAKfeCEw="
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 5,
      name = "path",
      visible = true,
      opacity = 1,
      offsetx = 32,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgF9ASbuQfaBbjBqNvIA6NuIw8MhNtAdhKLBysYdRt5YNRt5IFRt40CcgAAlLUREw=="
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 19,
      name = "blueTile1",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFAwFCeAfaBaNgFIyCUTAKRsEoGAXUBwBo4ABi"
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 20,
      name = "blueTile2",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFo2AUjIJRMApGwSgYmiCEd6BdMArQAQCjYwBi"
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 36,
      name = "buttonsSecondRow",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {
        ["blue"] = "blueTile",
        ["yellow"] = "yellowTile"
      },
      encoding = "base64",
      compression = "zlib",
      data = "eJztwTEBAAAAwqD1T20JT6AAAOBjClwAAQ=="
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 37,
      name = "buttonsThirdRow",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {
        ["F1"] = "F1",
        ["paint"] = "paint grey"
      },
      encoding = "base64",
      compression = "zlib",
      data = "eJztwTEBAAAAwqD1T20JT6AAAOBjClwAAQ=="
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 17,
      name = "yellowTile1",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFo2AUjIKRBYJ4B9oFo2AUjIJRMHwBAAqJAGA="
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 18,
      name = "yellowTile2",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFo2AUjIJRgA0E8Q60C0bBKBgFo2DoAQD7ogBg"
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 7,
      name = "cars",
      visible = true,
      opacity = 1,
      offsetx = 13.1667,
      offsety = -4.5,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJztzkERACAIBMB7Qf+vhtHBMBpDAvCH0dsEC9DvTIGl2YvY9tcpemsCdMlexIa/ZtEbERG97QKI+gY9"
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 9,
      name = "streetDetails",
      visible = true,
      opacity = 1,
      offsetx = 0.25,
      offsety = -0.5,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFo2AUDEfAycvQMNBuwAX0eAav24YC4OAdaBfgBsC4pSmQ4iGMpWnsBlzAlIcwNht126jbRoDbABfxD9Q="
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 8,
      name = "Tile Layer 8",
      visible = true,
      opacity = 1,
      offsetx = 19.6667,
      offsety = 37.3333,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFo2AUjIJRMBSALjtDgw4QD7Q7sIEgoLsCB6nbRsEoGAX0BQBrGwMZ"
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 11,
      name = "city2",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJztzjEOABAQRFGF7ZBwfyTroibRyEanoJiX/P6rd07RQAElU0Sv6PZWUTN1vh1lWRX5720X8BdNSV5fERER0Y0J4oYSVg=="
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 10,
      name = "details",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYCAMJNgYGBTZiFBIZbCDDYFxgTOsA+M2NaC96kCswQrh32FhYLgLxfdYIGIubBA8EECNHZWfwQrGDQPiGCTQDA2PFqRwmQx06xR27OoHCiQB3WeLFncXWAfGLaOAMsA+QHmQGMA6iN02CkbBKBgF5AIAs9MNew=="
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 12,
      name = "text",
      visible = true,
      opacity = 1,
      offsetx = 0.666667,
      offsety = -8,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJzt0kkKgDAQRNHaxeEIeivn8azex3GrKFggIgguJa3kw4Msi9DA/5stYKHABkKKKKaEUsoop4JKqqi2da/WX6uAjnoaaFO6F12NgrY81TiA5wK+e7wlNAn+t/u9rYK2fvHezrfOJN+byWR6rx2qmhgi"
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 13,
      name = "text",
      visible = false,
      opacity = 1,
      offsetx = 8.94602,
      offsety = 7.99905,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFo2BogwNcA+2CUTCSAHJ6G017o2AUjIJRgAkAIqgCXw=="
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 22,
      name = "fruit1",
      visible = true,
      opacity = 1,
      offsetx = 0.363636,
      offsety = -3,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFo2AUjIJRgA185xpoF4yCUTAKRsHQAwBL2QEC"
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 23,
      name = "fruit2",
      visible = true,
      opacity = 1,
      offsetx = 0.363636,
      offsety = -3,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFo2AUUAN85xpoF4yCUTAKRsEoGAUDDwAhywEC"
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 24,
      name = "fruit3",
      visible = true,
      opacity = 1,
      offsetx = 0.363636,
      offsety = -3,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFAwG+cw20C0bBKBgFo2AUjIJRMAqoDwD3rgEC"
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 25,
      name = "fruit4",
      visible = true,
      opacity = 1,
      offsetx = 0.363636,
      offsety = -3,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFo2AUjIJRMApGBvjONdAuGAWjYPgDAHXnAQI="
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 26,
      name = "fruit5",
      visible = true,
      opacity = 1,
      offsetx = 0.363636,
      offsety = -3,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFo2AUjIJRMApGwSgYmuA710C7YBSgAwCf9QEC"
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 2,
      name = "buttons",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJztzskNggAQQNE5w0Fc2nBtAxXbcIF2XKAN1zYUtQ1APfMTGuBgwhzmJ+/+RSzLsqx/tnVEdtjjgBiJ0/RV1ZGPE8644Iqbkrc7Hw+keOKFt5K3jI8cBT744qfkreWKeGijgy56btNXVX0+BhhihDEmSt58PqaYYY4ACyVvSz5WWGODEJGStzqVXZ4acQ=="
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 32,
      name = "answer",
      visible = false,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {
        ["numObejcts"] = 6
      },
      objects = {
        {
          id = 19,
          name = "answer1",
          type = "",
          shape = "rectangle",
          x = 320.651,
          y = 72.0109,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 20,
          name = "answer2",
          type = "",
          shape = "rectangle",
          x = 344.162,
          y = 71.9409,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 21,
          name = "answer3",
          type = "",
          shape = "rectangle",
          x = 368.009,
          y = 72.0401,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 26,
          name = "answer4",
          type = "",
          shape = "rectangle",
          x = 320.419,
          y = 136,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 27,
          name = "answer5",
          type = "",
          shape = "rectangle",
          x = 344.097,
          y = 135.914,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 29,
          name = "answer6",
          type = "",
          shape = "rectangle",
          x = 368.19,
          y = 135.969,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 30,
          name = "answer7",
          type = "",
          shape = "rectangle",
          x = 392.156,
          y = 135.938,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 33,
      name = "grass",
      visible = false,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {
        ["numObjects"] = 5
      },
      objects = {
        {
          id = 31,
          name = "grass1",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 0,
          width = 250.364,
          height = 125.273,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 32,
          name = "grass2",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 147.091,
          width = 252,
          height = 124.909,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 33,
          name = "grass3",
          type = "",
          shape = "rectangle",
          x = 275.375,
          y = 0.03125,
          width = 109.25,
          height = 272,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 34,
          name = "grass4",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 0,
          width = 384,
          height = 28.25,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 35,
          name = "grass5",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 243.5,
          width = 384,
          height = 28.5,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 15,
      name = "yellowTile",
      visible = false,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {
        ["numObjects"] = 2
      },
      objects = {
        {
          id = 1,
          name = "yellowTile1",
          type = "",
          shape = "rectangle",
          x = 99.9086,
          y = 135.546,
          width = 0.363636,
          height = 0.545455,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2,
          name = "yellowTile2",
          type = "",
          shape = "rectangle",
          x = 269.609,
          y = 135.344,
          width = 0.375,
          height = 0.375,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 35,
      name = "player",
      visible = false,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      objects = {
        {
          id = 37,
          name = "player",
          type = "",
          shape = "rectangle",
          x = 96,
          y = 128,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 16,
      name = "blueTile",
      visible = false,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {
        ["numObjects"] = 2
      },
      objects = {
        {
          id = 3,
          name = "blueTile1",
          type = "",
          shape = "rectangle",
          x = 264.348,
          y = 33.5415,
          width = 0.363636,
          height = 0.363636,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 4,
          name = "blueTile2",
          type = "",
          shape = "rectangle",
          x = 263.962,
          y = 237.603,
          width = 0.5,
          height = 0.5,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 21,
      name = "fruit",
      visible = false,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {
        ["numObjects"] = 5
      },
      objects = {
        {
          id = 5,
          name = "fruit1",
          type = "",
          shape = "rectangle",
          x = 269.672,
          y = 134.532,
          width = 0.1875,
          height = 0.1875,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 8,
          name = "fruit2",
          type = "",
          shape = "rectangle",
          x = 270.151,
          y = 87.3755,
          width = 0.545455,
          height = 0.363636,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 11,
          name = "fruit3",
          type = "",
          shape = "rectangle",
          x = 263.878,
          y = 33.1977,
          width = 0.363636,
          height = 0.545455,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 15,
          name = "fruit4",
          type = "",
          shape = "rectangle",
          x = 269.577,
          y = 183.787,
          width = 0.909091,
          height = 0.545455,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 16,
          name = "fruit5",
          type = "",
          shape = "rectangle",
          x = 263.87,
          y = 237.672,
          width = 0.545455,
          height = 0.545455,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 27,
      name = "apple1",
      visible = true,
      opacity = 1,
      offsetx = 9.66667,
      offsety = -2.66667,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFo2AUjIJRMFLAd66BdsEoGAWjYLgDAHb2AQI="
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 28,
      name = "apple2",
      visible = true,
      opacity = 1,
      offsetx = 9.66667,
      offsety = -2.66667,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFo2AUjIJRMJLAd66BdsEoGAWjYDgDAHLyAQI="
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 29,
      name = "apple3",
      visible = true,
      opacity = 1,
      offsetx = 9.66667,
      offsety = -2.66667,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFo2AUjIJRMNLAd66BdsEoGAWjYLgCAG7uAQI="
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 30,
      name = "apple4",
      visible = true,
      opacity = 1,
      offsetx = 9.66667,
      offsety = -2.66667,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFo2AUjIJRMBLBd66BdsEoGAWjYDgCAGrqAQI="
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 31,
      name = "apple5",
      visible = true,
      opacity = 1,
      offsetx = 9.66667,
      offsety = -2.66667,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFo2AUjIJRMFLBd66BdsEoGAWjYLgBAGbmAQI="
    }
  }
}
