return {
  version = "1.2",
  luaversion = "5.1",
  tiledversion = "2020.01.22",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 39,
  height = 17,
  tilewidth = 16,
  tileheight = 16,
  nextlayerid = 40,
  nextobjectid = 53,
  properties = {},
  tilesets = {
    {
      name = "UIpackSheet_transparent",
      firstgid = 1,
      tilewidth = 16,
      tileheight = 16,
      spacing = 2,
      margin = 0,
      columns = 30,
      image = "../tileset/Tilemap/UIpackSheet_transparent.png",
      imagewidth = 538,
      imageheight = 592,
      objectalignment = "unspecified",
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 16,
        height = 16
      },
      properties = {},
      terrains = {},
      tilecount = 990,
      tiles = {}
    },
    {
      name = "roguelikeCity",
      firstgid = 991,
      tilewidth = 16,
      tileheight = 16,
      spacing = 1,
      margin = 0,
      columns = 37,
      image = "../tileset/Tilemap/roguelikeCity.png",
      imagewidth = 628,
      imageheight = 475,
      objectalignment = "unspecified",
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 16,
        height = 16
      },
      properties = {},
      terrains = {},
      tilecount = 1036,
      tiles = {}
    },
    {
      name = "functionsTextTiles",
      firstgid = 2027,
      tilewidth = 16,
      tileheight = 16,
      spacing = 0,
      margin = 0,
      columns = 30,
      image = "../graphics/functionsTextTiles.png",
      imagewidth = 480,
      imageheight = 480,
      objectalignment = "unspecified",
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 16,
        height = 16
      },
      properties = {},
      terrains = {},
      tilecount = 900,
      tiles = {}
    },
    {
      name = "test",
      firstgid = 2927,
      tilewidth = 16,
      tileheight = 16,
      spacing = 0,
      margin = 0,
      columns = 27,
      image = "../tileset/Tilemap/test.png",
      imagewidth = 432,
      imageheight = 288,
      objectalignment = "unspecified",
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 16,
        height = 16
      },
      properties = {},
      terrains = {},
      tilecount = 486,
      tiles = {}
    }
  },
  layers = {
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 14,
      name = "info",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {
        ["F0"] = 3,
        ["F1"] = 3,
        ["blueTile"] = true,
        ["door"] = false,
        ["face"] = "up",
        ["fruit"] = true,
        ["fruitsTotal"] = 5,
        ["grass"] = true,
        ["greyTile"] = false,
        ["numFunc"] = 2,
        ["totalSize"] = 6,
        ["yellowTile"] = true
      },
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFo2AUjIJRMApGNgjnHmgXDD8wGqYjFwAAEXwAxQ=="
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 1,
      name = "background",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJwz5WFgMKUA17AzMNQC8SIoTQ7GpZcSd4HwQqjZtMDE2P+emYHhIw480G77BHTDVxyYVu4i1W2fgViMBRUPlnATZxl86W3UbaNuG05u6x/EbhvM4TbqtlG3DQa3AQBbxl60"
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 38,
      name = "background2",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYKAtmM5Kup4iMvTQ0hxkQI5/aGUOpf4L52ZgCMOCqQEo9R+13EELMJLdRkmao7XbKElz4VR0G7XLHWq6jVrlFwxQ023UBrjcRu34Icc8XG6jdvyQYx414pQWdS8IUMNt1A5jUgC2cCEnrOjVtiEnrGB6AIx0Euc="
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 39,
      name = "parkDetails",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFQxncZB9oF6CCC6wMDJJstLeHHH9/B7rNDui2b6wQPgcd3Eku0B0gtw229DRcwGi4jgJSASzNgMrTC6wD6xZsAL08BYGBTufsVCw3qe0XHSS3DXQ40QMAALQvDd8="
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 36,
      name = "buttonsSecondRow",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {
        ["blue"] = "blueTile",
        ["yellow"] = "yellowTile"
      },
      encoding = "base64",
      compression = "zlib",
      data = "eJztwTEBAAAAwqD1T20JT6AAAOBjClwAAQ=="
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 37,
      name = "buttonsThirdRow",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {
        ["F1"] = "F1"
      },
      encoding = "base64",
      compression = "zlib",
      data = "eJztwTEBAAAAwqD1T20JT6AAAOBjClwAAQ=="
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 12,
      name = "text",
      visible = true,
      opacity = 1,
      offsetx = 15.6667,
      offsety = -3,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJzt0jsKgDAQhOGxitEj+Lz/KbyPz1ZN1AELQbARJIvsDx+kHMIC/2+OgYVWcuRpo51ggYhyKqikimobenX4WgN01NNA3oRedDUK2vJUkwBZyttKz7eEJsH/dr83J2ir3tu7JN+bpmnfdQBP1Rky"
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 22,
      name = "fruit1",
      visible = true,
      opacity = 1,
      offsetx = 0.363636,
      offsety = -3,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFo2AUjALag+9cA+2CUTAKRsEoGAX0AAAAnAEC"
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 23,
      name = "fruit2",
      visible = true,
      opacity = 1,
      offsetx = 0.363636,
      offsety = -3,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFo2AUkAK+cw20C0bBKBgFo2AUjILBCwA54wEC"
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 24,
      name = "fruit3",
      visible = true,
      opacity = 1,
      offsetx = 0.363636,
      offsety = -3,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFIxV85xpoF4yCUTAKRsEoGAWjYLgBAHMqAQI="
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 25,
      name = "fruit4",
      visible = true,
      opacity = 1,
      offsetx = 0.363636,
      offsety = -3,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFo4CB4TvXQLtgFIyCUTAKRsEoGAXDAQAAZx4BAg=="
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 26,
      name = "fruit5",
      visible = true,
      opacity = 1,
      offsetx = 0.363636,
      offsety = -3,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFowAVfOcaaBeMglEwCkbBKBgFo2CoAgBbEgEC"
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 2,
      name = "buttons",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJztzskNggAQQNE5w0Fc2nBtAxXbcIF2XKAN1zYUtQ1APfMTGuBgwhzmJ+/+RSzLsqx/tnVEdtjjgBiJ0/RV1ZGPE8644Iqbkrc7Hw+keOKFt5K3jI8cBT744qfkreWKeGijgy56btNXVX0+BhhihDEmSt58PqaYYY4ACyVvSz5WWGODEJGStzqVXZ4acQ=="
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 32,
      name = "answer",
      visible = false,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {
        ["numObejcts"] = 6
      },
      objects = {
        {
          id = 19,
          name = "answer1",
          type = "",
          shape = "rectangle",
          x = 335.589,
          y = 76.8859,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 20,
          name = "answer2",
          type = "",
          shape = "rectangle",
          x = 359.435,
          y = 76.85,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 21,
          name = "answer3",
          type = "",
          shape = "rectangle",
          x = 383.464,
          y = 76.8583,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 26,
          name = "answer4",
          type = "",
          shape = "rectangle",
          x = 335.601,
          y = 140.818,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 27,
          name = "answer5",
          type = "",
          shape = "rectangle",
          x = 359.523,
          y = 141.036,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 29,
          name = "answer6",
          type = "",
          shape = "rectangle",
          x = 383.554,
          y = 140.941,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 33,
      name = "grass",
      visible = false,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {
        ["numObjects"] = 5
      },
      objects = {
        {
          id = 31,
          name = "grass1",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 0,
          width = 154.364,
          height = 299.273,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 32,
          name = "grass2",
          type = "",
          shape = "rectangle",
          x = 180.667,
          y = 69.7577,
          width = 168.667,
          height = 202.242,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 33,
          name = "grass3",
          type = "",
          shape = "rectangle",
          x = 272.042,
          y = 0.03125,
          width = 112.583,
          height = 272,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 34,
          name = "grass4",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 0,
          width = 384,
          height = 44.25,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 35,
          name = "grass5",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 243.5,
          width = 384,
          height = 28.5,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 15,
      name = "yellowTile",
      visible = false,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {
        ["numObjects"] = 8
      },
      objects = {
        {
          id = 1,
          name = "yellowTile1",
          type = "",
          shape = "rectangle",
          x = 167.971,
          y = 225.233,
          width = 0.363636,
          height = 0.357955,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2,
          name = "yellowTile2",
          type = "",
          shape = "rectangle",
          x = 167.953,
          y = 209.177,
          width = 0.375,
          height = 0.375,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 39,
          name = "yellowTile3",
          type = "",
          shape = "rectangle",
          x = 167.881,
          y = 193.759,
          width = 0.363636,
          height = 0.357955,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 40,
          name = "yellowTile4",
          type = "",
          shape = "rectangle",
          x = 168.068,
          y = 178.384,
          width = 0.363636,
          height = 0.357955,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 41,
          name = "yellowTile5",
          type = "",
          shape = "rectangle",
          x = 167.881,
          y = 162.009,
          width = 0.363636,
          height = 0.357955,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 42,
          name = "yellowTile6",
          type = "",
          shape = "rectangle",
          x = 167.943,
          y = 145.634,
          width = 0.363636,
          height = 0.357955,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 43,
          name = "yellowTile7",
          type = "",
          shape = "rectangle",
          x = 167.756,
          y = 129.696,
          width = 0.363636,
          height = 0.357955,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 45,
          name = "yellowTile8",
          type = "",
          shape = "rectangle",
          x = 167.636,
          y = 50.7301,
          width = 0.363636,
          height = 0.357955,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 35,
      name = "player",
      visible = false,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      objects = {
        {
          id = 37,
          name = "player",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 224,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 16,
      name = "blueTile",
      visible = false,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {
        ["numObjects"] = 9
      },
      objects = {
        {
          id = 3,
          name = "blueTile1",
          type = "",
          shape = "rectangle",
          x = 167.723,
          y = 113.854,
          width = 0.363636,
          height = 0.363636,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 4,
          name = "blueTile2",
          type = "",
          shape = "rectangle",
          x = 167.774,
          y = 97.6655,
          width = 0.5,
          height = 0.5,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 46,
          name = "blueTile3",
          type = "",
          shape = "rectangle",
          x = 167.787,
          y = 82.0999,
          width = 0.363636,
          height = 0.363636,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 47,
          name = "blueTile4",
          type = "",
          shape = "rectangle",
          x = 167.838,
          y = 65.9114,
          width = 0.5,
          height = 0.5,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 48,
          name = "blueTile5",
          type = "",
          shape = "rectangle",
          x = 189.563,
          y = 55.0625,
          width = 0.5,
          height = 0.5,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 49,
          name = "blueTile6",
          type = "",
          shape = "rectangle",
          x = 205.375,
          y = 55.25,
          width = 0.5,
          height = 0.5,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 50,
          name = "blueTile7",
          type = "",
          shape = "rectangle",
          x = 221.75,
          y = 55.375,
          width = 0.5,
          height = 0.5,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 51,
          name = "blueTile9",
          type = "",
          shape = "rectangle",
          x = 253.125,
          y = 55.375,
          width = 0.5,
          height = 0.5,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 52,
          name = "blueTile8",
          type = "",
          shape = "rectangle",
          x = 236.875,
          y = 55.25,
          width = 0.5,
          height = 0.5,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 21,
      name = "fruit",
      visible = false,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {
        ["numObjects"] = 5
      },
      objects = {
        {
          id = 5,
          name = "fruit1",
          type = "",
          shape = "rectangle",
          x = 167.922,
          y = 113.657,
          width = 0.1875,
          height = 0.1875,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 8,
          name = "fruit2",
          type = "",
          shape = "rectangle",
          x = 167.401,
          y = 82.0005,
          width = 0.545455,
          height = 0.363636,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 11,
          name = "fruit3",
          type = "",
          shape = "rectangle",
          x = 173.253,
          y = 55.0727,
          width = 0.363636,
          height = 0.545455,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 15,
          name = "fruit4",
          type = "",
          shape = "rectangle",
          x = 220.577,
          y = 55.287,
          width = 0.909091,
          height = 0.545455,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 16,
          name = "fruit5",
          type = "",
          shape = "rectangle",
          x = 267.745,
          y = 56.047,
          width = 0.545455,
          height = 0.545455,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 27,
      name = "apple1",
      visible = true,
      opacity = 1,
      offsetx = 9.66667,
      offsety = -2.66667,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFo2AUjIJRMFLAd66BdsEoGAWjYLgDAHb2AQI="
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 28,
      name = "apple2",
      visible = true,
      opacity = 1,
      offsetx = 9.66667,
      offsety = -2.66667,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFo2AUjIJRMJLAd66BdsEoGAWjYDgDAHLyAQI="
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 29,
      name = "apple3",
      visible = true,
      opacity = 1,
      offsetx = 9.66667,
      offsety = -2.66667,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFo2AUjIJRMNLAd66BdsEoGAWjYLgCAG7uAQI="
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 30,
      name = "apple4",
      visible = true,
      opacity = 1,
      offsetx = 9.66667,
      offsety = -2.66667,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFo2AUjIJRMBLBd66BdsEoGAWjYDgCAGrqAQI="
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 31,
      name = "apple5",
      visible = true,
      opacity = 1,
      offsetx = 9.66667,
      offsety = -2.66667,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFo2AUjIJRMFLBd66BdsEoGAWjYLgBAGbmAQI="
    }
  }
}
