return {
  version = "1.2",
  luaversion = "5.1",
  tiledversion = "2020.01.22",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 39,
  height = 17,
  tilewidth = 16,
  tileheight = 16,
  nextlayerid = 114,
  nextobjectid = 187,
  properties = {},
  tilesets = {
    {
      name = "UIpackSheet_transparent",
      firstgid = 1,
      tilewidth = 16,
      tileheight = 16,
      spacing = 2,
      margin = 0,
      columns = 30,
      image = "../tileset/Tilemap/UIpackSheet_transparent.png",
      imagewidth = 538,
      imageheight = 592,
      objectalignment = "unspecified",
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 16,
        height = 16
      },
      properties = {},
      terrains = {},
      tilecount = 990,
      tiles = {}
    },
    {
      name = "roguelikeCity",
      firstgid = 991,
      tilewidth = 16,
      tileheight = 16,
      spacing = 1,
      margin = 0,
      columns = 37,
      image = "../tileset/Tilemap/roguelikeCity.png",
      imagewidth = 628,
      imageheight = 475,
      objectalignment = "unspecified",
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 16,
        height = 16
      },
      properties = {},
      terrains = {},
      tilecount = 1036,
      tiles = {}
    },
    {
      name = "functionsTextTiles",
      firstgid = 2027,
      tilewidth = 16,
      tileheight = 16,
      spacing = 0,
      margin = 0,
      columns = 30,
      image = "../graphics/functionsTextTiles.png",
      imagewidth = 480,
      imageheight = 480,
      objectalignment = "unspecified",
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 16,
        height = 16
      },
      properties = {},
      terrains = {},
      tilecount = 900,
      tiles = {}
    },
    {
      name = "test",
      firstgid = 2927,
      tilewidth = 16,
      tileheight = 16,
      spacing = 0,
      margin = 0,
      columns = 27,
      image = "../tileset/Tilemap/test.png",
      imagewidth = 432,
      imageheight = 288,
      objectalignment = "unspecified",
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 16,
        height = 16
      },
      properties = {},
      terrains = {},
      tilecount = 486,
      tiles = {}
    }
  },
  layers = {
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 14,
      name = "info",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {
        ["F0"] = 5,
        ["F1"] = 0,
        ["blueTile"] = true,
        ["door"] = false,
        ["face"] = "up",
        ["fruit"] = true,
        ["fruitsTotal"] = 34,
        ["grass"] = true,
        ["greyTile"] = false,
        ["numFunc"] = 1,
        ["totalSize"] = 5,
        ["yellowTile"] = true
      },
      encoding = "base64",
      compression = "zlib",
      data = "eJzr5mZg6B7Fo3gUj+JRPIpHMA4fBG4Ybng0TEcuBgCJUYQi"
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 1,
      name = "background",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxbxM7AsGgUj+JRPIpH8SgeRLh/ELhhFI/iUUweBgCxzbWs"
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 38,
      name = "background2",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJzNlEkOgCAMRbvAcF/voS7ZcwTjXRxOY12QAGFoQAokb1NIefkMWgLME4CWeRRxXS22j7+nmaM6U9dRSWVg5qg5ceUZIjW4XRYBsCKbcN16ZWOzo9ODHMLNrrfXx4lOF3IT3P5+B5T+fi3m1vodhPr7tVHONETOrfXZ1rj1/uM49inJn8utJP+UW8u7Futt11NuLe9arLciunFlNQImkxdHsKWx"
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 40,
      name = "path",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJzlVFsKwCAM89/7rfT+FxmDFUKwPj6MjAVEW4WE1LaU78BqPx7ldyC4nDgjfu4d1lU1+uzlctid4lZe5Z0PfMvyCsxqy2q/CwY1GmljjQogtwF/aI4V/+5En7J3vb5VwRI9LW3op0IXzojszDNFPUN6Z4yVM2SlpvxeBf5LqO1UnyJmfDuFrL5892fcm1kqHg=="
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 39,
      name = "parkDetails",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgYsIidMKa3O0h1H0wPvdxKrNvoZScpbkLW850V03wfFkyxh6yoNK38QUq4YXM7CHwjw43EhhmpcUppuJHiLmqnN0Jm0sJt5MQdvdwGA7jSHS3cNRBlL7luo1bc0cJt9AADlReoURcMZLiR4t7B4AZi3UbPsCTkNgDl3ZAj"
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 36,
      name = "buttonsSecondRow",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {
        ["blue"] = "blueTile",
        ["yellow"] = "yellowTile"
      },
      encoding = "base64",
      compression = "zlib",
      data = "eJztwTEBAAAAwqD1T20JT6AAAOBjClwAAQ=="
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 37,
      name = "buttonsThirdRow",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJztwTEBAAAAwqD1T20JT6AAAOBjClwAAQ=="
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 12,
      name = "text",
      visible = true,
      opacity = 1,
      offsetx = 15.6667,
      offsety = -3,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJzt0DkKgEAQRNHKxnGOoLdyX8/qfVxTBcHKDMS4HekPDzosGvh/ewAclFggpYxyKqikimpqqKWOeiu9Wr7RABPNtNBppBfdrR/a8tYQApEDYve8pdo8+JumaZrmdxegRhBN"
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 22,
      name = "fruit1",
      visible = true,
      opacity = 1,
      offsetx = 0.363636,
      offsety = -3,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFo2AUjALagO9cA+2CUTAKRsEoGAX0BgAMqAEC"
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 23,
      name = "fruit2",
      visible = true,
      opacity = 1,
      offsetx = 0.363636,
      offsety = -3,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFo2AUjAL6ge9cA+2CUTAKRsEoGAW0BAD4hQEC"
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 24,
      name = "fruit3",
      visible = true,
      opacity = 1,
      offsetx = 0.363636,
      offsety = -3,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFo2AUjIJRMArwg+9cA+2CUTAKRsFQAQA+vgEC"
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 25,
      name = "fruit4",
      visible = true,
      opacity = 1,
      offsetx = 0.363636,
      offsety = -3,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFo2AUjIJRMFTAd66BdsEoGAWjYBTgBwC3NgEC"
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 26,
      name = "fruit5",
      visible = true,
      opacity = 1,
      offsetx = 0.363636,
      offsety = -3,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFo2AUjIJRMApGwUgE37kG2gWjYDgCAGTIAQI="
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 113,
      name = "fruit6",
      visible = true,
      opacity = 1,
      offsetx = 0.818182,
      offsety = -2.90909,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFo2AUjIJRMApGwSgYBcSA71wD7YLBDwAvhQEC"
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 112,
      name = "fruit7",
      visible = true,
      opacity = 1,
      offsetx = 0.818182,
      offsety = -2.90909,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFo2AUjIJRMApGwUgC37kG2gWjYDgDAGzQAQI="
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 111,
      name = "fruit8",
      visible = true,
      opacity = 1,
      offsetx = 0.818182,
      offsety = -2.90909,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFo2AUjIJRMApGAbXAd66BdsEoGAUDCwARgwEC"
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 110,
      name = "fruit9",
      visible = true,
      opacity = 1,
      offsetx = 0.818182,
      offsety = -2.90909,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFo2AUjIJRMApQwXeugXbBKBgFo2CoAgBOzgEC"
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 109,
      name = "fruit10",
      visible = true,
      opacity = 1,
      offsetx = 0.818182,
      offsety = -2.90909,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFo2AUjIJRMFDgO9dAu2AUjIJRMAqoCwDnZgEC"
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 108,
      name = "fruit11",
      visible = true,
      opacity = 1,
      offsetx = 0.818182,
      offsety = -2.90909,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFo2AUjILhDb5zDbQLRsEoGAWjYOQAAIQRAQI="
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 107,
      name = "fruit12",
      visible = true,
      opacity = 1,
      offsetx = 0.818182,
      offsety = -2.90909,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFo2AUDAXwnWugXTAKRsEoGAWjYBQQBgDBXAEC"
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 106,
      name = "fruit13",
      visible = true,
      opacity = 1,
      offsetx = 0.818182,
      offsety = -2.90909,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFo2AUDCXwnWugXTAKRsEoGAWjYBTgBgC5VAEC"
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 105,
      name = "fruit14",
      visible = true,
      opacity = 1,
      offsetx = 0.818182,
      offsety = -2.90909,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFwxF85xpoF4yCUTAKRsEoGAWjYCQCAJdOAQI="
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 104,
      name = "fruit15",
      visible = true,
      opacity = 1,
      offsetx = 0.818182,
      offsety = -2.90909,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFlIDvXAPtglEwCkbBKBgFo2AUjILBAwAv9QEC"
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 103,
      name = "fruit16",
      visible = true,
      opacity = 1,
      offsetx = 0.818182,
      offsety = -2.90909,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBg64DvXQLtgFIyCUTAKRsEoGAWjYBTgAwDEiQEC"
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 102,
      name = "fruit17",
      visible = true,
      opacity = 1,
      offsetx = 0.818182,
      offsety = -2.90909,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFo2AUjIKRAb5zDbQLRsEoGAWjYPgDAHwJAQI="
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 101,
      name = "fruit18",
      visible = true,
      opacity = 1,
      offsetx = 0.818182,
      offsety = -2.90909,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFo2AUjALqgu9cA+2CUTAKRsEoGAUDBQAUsAEC"
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 100,
      name = "fruit19",
      visible = true,
      opacity = 1,
      offsetx = 0.818182,
      offsety = -2.90909,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBi64DvXQLtgFIyCUTAKRsEoGAWjYBQgAwC0eQEC"
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 99,
      name = "fruit20",
      visible = true,
      opacity = 1,
      offsetx = 0.818182,
      offsety = -2.90909,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFtATfuQbaBaNgFIyCUTAKRsEoGAX0AwAP1QEC"
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 98,
      name = "fruit21",
      visible = true,
      opacity = 1,
      offsetx = 0.818182,
      offsety = -2.90909,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBh+4DvXQLtgFIyCUTAKRsEoGAWjYGQCAJxhAQI="
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 97,
      name = "fruit22",
      visible = true,
      opacity = 1,
      offsetx = 0.818182,
      offsety = -2.90909,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgF9AbfuQbaBaNgFIyCUTAKRsEoGAW0AQD7sgEC"
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 96,
      name = "fruit23",
      visible = true,
      opacity = 1,
      offsetx = 0.818182,
      offsety = -2.90909,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFowABvnMNtAtGwSgYBaNgFIyCUTCUAQBfFgEC"
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 95,
      name = "fruit24",
      visible = true,
      opacity = 1,
      offsetx = 0.818182,
      offsety = -2.90909,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFo2AUDFfwnWugXTAKRsEoGAWjYKQBAI0oAQI="
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 94,
      name = "fruit25",
      visible = true,
      opacity = 1,
      offsetx = 0.818182,
      offsety = -2.90909,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFo2AUjAL6g+9cA+2CUTAKRsEoGAW0AADwfQEC"
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 93,
      name = "fruit26",
      visible = true,
      opacity = 1,
      offsetx = 0.818182,
      offsety = -2.90909,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFo2AUjIJRgAy+cw20C0bBKBgFo2DoAgBT4QEC"
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 92,
      name = "fruit27",
      visible = true,
      opacity = 1,
      offsetx = 0.818182,
      offsety = -2.90909,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFo2AUjIJRMBTAd66BdsEoGAWjYBQQBgC7OgEC"
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 91,
      name = "fruit28",
      visible = true,
      opacity = 1,
      offsetx = 0.818182,
      offsety = -2.90909,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFo2AUjIJRMJTAd66BdsEoGAWjYBTgBgCzMgEC"
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 90,
      name = "fruit29",
      visible = true,
      opacity = 1,
      offsetx = 0.818182,
      offsety = -2.90909,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFo2AUjIJRMAqoA75zDbQLRsEoGAUDDQAWlgEC"
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 89,
      name = "fruit30",
      visible = true,
      opacity = 1,
      offsetx = 0.818182,
      offsety = -2.90909,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFo2AUjALag+9cA+2CUTAKRsEoGAX0AAAAnAEC"
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 88,
      name = "fruit31",
      visible = true,
      opacity = 1,
      offsetx = 0.818182,
      offsety = -2.90909,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFo2AUkAO+cw20C0bBKBgFo2AUjILBBwAx2wEC"
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 87,
      name = "fruit32",
      visible = true,
      opacity = 1,
      offsetx = 0.818182,
      offsety = -2.90909,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFtACTuQbaBaNgFIyCUTAKRgFl4PtoXTYKyAAAzF0Bnw=="
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 86,
      name = "fruit33",
      visible = true,
      opacity = 1,
      offsetx = 0.818182,
      offsety = -2.90909,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFo2AUjIJRMApGwSgYBZSC71wD7YLBAQATaQEC"
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 85,
      name = "fruit34",
      visible = true,
      opacity = 1,
      offsetx = 0.818182,
      offsety = -2.90909,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFo2AUjIJRMApGwSiAgO9cA+2CUTDUAQBQtAEC"
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 2,
      name = "buttons",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJzt0ckNgmAUReG3hoWgtiEObTjRhjiUI4q24diGorYhDmuPgZUbjBtezH+Tb3+SK2Jm9t+bWiIhZpgjwgJLq+iydFc67h+epi13pu23rehYY4MtdtgraTvQcUSME864KGl7f5rglv35UPRpyRZx4KKMCqp20VXpanR4qKOBJlpK2tp0dNBFD334StoGdAQYYoQxJkravtkLlMIy3Q=="
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 32,
      name = "answer",
      visible = false,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {
        ["numObejcts"] = 6
      },
      objects = {
        {
          id = 19,
          name = "answer1",
          type = "",
          shape = "rectangle",
          x = 335.589,
          y = 76.8859,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 20,
          name = "answer2",
          type = "",
          shape = "rectangle",
          x = 359.435,
          y = 76.85,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 21,
          name = "answer3",
          type = "",
          shape = "rectangle",
          x = 383.464,
          y = 76.8583,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 26,
          name = "answer4",
          type = "",
          shape = "rectangle",
          x = 406.601,
          y = 76.3182,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 27,
          name = "answer5",
          type = "",
          shape = "rectangle",
          x = 431.523,
          y = 75.5362,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 33,
      name = "grass",
      visible = false,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {
        ["numObjects"] = 23
      },
      objects = {
        {
          id = 32,
          name = "grass2",
          type = "",
          shape = "rectangle",
          x = -27.4167,
          y = 179.341,
          width = 56.6667,
          height = 54.2423,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 33,
          name = "grass3",
          type = "",
          shape = "rectangle",
          x = 260.163,
          y = 0.03125,
          width = 125.917,
          height = 272,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 157,
          name = "grass1",
          type = "",
          shape = "rectangle",
          x = -0.5,
          y = -14.5,
          width = 282.5,
          height = 28,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 159,
          name = "grass4",
          type = "",
          shape = "rectangle",
          x = -22,
          y = -33.5,
          width = 33,
          height = 324.5,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 160,
          name = "grass5",
          type = "",
          shape = "rectangle",
          x = -19,
          y = 258,
          width = 296.5,
          height = 52.5,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 163,
          name = "grass6",
          type = "",
          shape = "rectangle",
          x = 153,
          y = 184.5,
          width = 28.5,
          height = 14.5,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 165,
          name = "grass7",
          type = "",
          shape = "rectangle",
          x = 150.5,
          y = 205.5,
          width = 18,
          height = 63.5,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 167,
          name = "grass8",
          type = "",
          shape = "rectangle",
          x = 158,
          y = 233,
          width = 24,
          height = 31.5,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 168,
          name = "grass9",
          type = "",
          shape = "rectangle",
          x = 90.5,
          y = 71.5,
          width = 25,
          height = 28,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 169,
          name = "grass10",
          type = "",
          shape = "rectangle",
          x = 90.5,
          y = 8,
          width = 24,
          height = 34,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 171,
          name = "grass11",
          type = "",
          shape = "rectangle",
          x = 4.5,
          y = 11,
          width = 49.5,
          height = 13.5,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 173,
          name = "grass12",
          type = "",
          shape = "rectangle",
          x = -2.5,
          y = 117,
          width = 26,
          height = 38,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 174,
          name = "grass13",
          type = "",
          shape = "rectangle",
          x = 8.5,
          y = 69.5,
          width = 16.5,
          height = 15.5,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 175,
          name = "grass14",
          type = "",
          shape = "rectangle",
          x = 56.5,
          y = 182.5,
          width = 13,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 176,
          name = "grass15",
          type = "",
          shape = "rectangle",
          x = 21,
          y = 216,
          width = 35.5,
          height = 45.5,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 177,
          name = "grass16",
          type = "",
          shape = "rectangle",
          x = 157.5,
          y = 138.5,
          width = 23.5,
          height = 15,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 178,
          name = "grass17",
          type = "",
          shape = "rectangle",
          x = 106,
          y = 137.5,
          width = 14,
          height = 17,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 179,
          name = "grass18",
          type = "",
          shape = "rectangle",
          x = 51.5,
          y = 69.5,
          width = 6.5,
          height = 19.5,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 181,
          name = "grass19",
          type = "",
          shape = "rectangle",
          x = 106.5,
          y = 183.5,
          width = 13,
          height = 19.5,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 182,
          name = "grass20",
          type = "",
          shape = "rectangle",
          x = 100.5,
          y = 230,
          width = 24.5,
          height = 34,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 183,
          name = "grass21",
          type = "",
          shape = "rectangle",
          x = 146.5,
          y = 5.5,
          width = 71,
          height = 22,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 184,
          name = "grass22",
          type = "",
          shape = "rectangle",
          x = 244,
          y = 69,
          width = 48.5,
          height = 69,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 186,
          name = "grass23",
          type = "",
          shape = "rectangle",
          x = 215,
          y = 230.5,
          width = 66.5,
          height = 52,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 15,
      name = "yellowTile",
      visible = false,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {
        ["numObjects"] = 34
      },
      objects = {
        {
          id = 1,
          name = "yellowTile1",
          type = "",
          shape = "rectangle",
          x = 23.0961,
          y = 162.108,
          width = 0.363636,
          height = 0.357955,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2,
          name = "yellowTile2",
          type = "",
          shape = "rectangle",
          x = 21.283,
          y = 97.6546,
          width = 0.375,
          height = 0.375,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 39,
          name = "yellowTile3",
          type = "",
          shape = "rectangle",
          x = 18.7292,
          y = 49.8343,
          width = 0.363636,
          height = 0.357955,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 40,
          name = "yellowTile4",
          type = "",
          shape = "rectangle",
          x = 39.4015,
          y = 206.399,
          width = 0.363636,
          height = 0.357955,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 41,
          name = "yellowTile5",
          type = "",
          shape = "rectangle",
          x = 45.3655,
          y = 145.63,
          width = 0.363636,
          height = 0.357955,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 42,
          name = "yellowTile6",
          type = "",
          shape = "rectangle",
          x = 45.7917,
          y = 130.043,
          width = 0.363636,
          height = 0.357955,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 43,
          name = "yellowTile7",
          type = "",
          shape = "rectangle",
          x = 40.483,
          y = 33.5294,
          width = 0.363636,
          height = 0.357955,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 45,
          name = "yellowTile8",
          type = "",
          shape = "rectangle",
          x = 61.697,
          y = 97.5937,
          width = 0.363636,
          height = 0.357955,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 53,
          name = "yellowTile9",
          type = "",
          shape = "rectangle",
          x = 70.6655,
          y = 209.676,
          width = 0.363636,
          height = 0.357955,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 54,
          name = "yellowTile10",
          type = "",
          shape = "rectangle",
          x = 86.9709,
          y = 253.967,
          width = 0.363636,
          height = 0.357955,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 55,
          name = "yellowTile11",
          type = "",
          shape = "rectangle",
          x = 109.068,
          y = 210.446,
          width = 0.363636,
          height = 0.357955,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 56,
          name = "yellowTile12",
          type = "",
          shape = "rectangle",
          x = 72.7273,
          y = 132.73,
          width = 0.363636,
          height = 0.357955,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 57,
          name = "yellowTile13",
          type = "",
          shape = "rectangle",
          x = 94.3636,
          y = 118.003,
          width = 0.363636,
          height = 0.357955,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 58,
          name = "yellowTile14",
          type = "",
          shape = "rectangle",
          x = 71.8182,
          y = 18.821,
          width = 0.363636,
          height = 0.357955,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 59,
          name = "yellowTile15",
          type = "",
          shape = "rectangle",
          x = 136.061,
          y = 18.6089,
          width = 0.363636,
          height = 0.357955,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 60,
          name = "yellowTile16",
          type = "",
          shape = "rectangle",
          x = 118.216,
          y = 114.807,
          width = 0.363636,
          height = 0.357955,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 61,
          name = "yellowTile17",
          type = "",
          shape = "rectangle",
          x = 152.545,
          y = 113.639,
          width = 0.363636,
          height = 0.357955,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 62,
          name = "yellowTile18",
          type = "",
          shape = "rectangle",
          x = 167.892,
          y = 114.983,
          width = 0.363636,
          height = 0.357955,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 63,
          name = "yellowTile19",
          type = "",
          shape = "rectangle",
          x = 184.182,
          y = 114.185,
          width = 0.363636,
          height = 0.357955,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 64,
          name = "yellowTile20",
          type = "",
          shape = "rectangle",
          x = 168,
          y = 34.7301,
          width = 0.363636,
          height = 0.357955,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 66,
          name = "yellowTile21",
          type = "",
          shape = "rectangle",
          x = 199.455,
          y = 84.7301,
          width = 0.363636,
          height = 0.357955,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 67,
          name = "yellowTile22",
          type = "",
          shape = "rectangle",
          x = 177.402,
          y = 214.738,
          width = 0.363636,
          height = 0.357955,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 68,
          name = "yellowTile23",
          type = "",
          shape = "rectangle",
          x = 199.561,
          y = 253.745,
          width = 0.363636,
          height = 0.357955,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 69,
          name = "yellowTile24",
          type = "",
          shape = "rectangle",
          x = 231.568,
          y = 221.321,
          width = 0.363636,
          height = 0.357955,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 70,
          name = "yellowTile25",
          type = "",
          shape = "rectangle",
          x = 237.619,
          y = 194.866,
          width = 0.363636,
          height = 0.357955,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 71,
          name = "yellowTile26",
          type = "",
          shape = "rectangle",
          x = 247.545,
          y = 170.276,
          width = 0.363636,
          height = 0.357955,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 72,
          name = "yellowTile27",
          type = "",
          shape = "rectangle",
          x = 252.818,
          y = 151.094,
          width = 0.363636,
          height = 0.357955,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 73,
          name = "yellowTile28",
          type = "",
          shape = "rectangle",
          x = 222.182,
          y = 154.912,
          width = 0.363636,
          height = 0.357955,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 74,
          name = "yellowTile29",
          type = "",
          shape = "rectangle",
          x = 237.818,
          y = 133.457,
          width = 0.363636,
          height = 0.357955,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 75,
          name = "yellowTile30",
          type = "",
          shape = "rectangle",
          x = 237.636,
          y = 118.185,
          width = 0.363636,
          height = 0.357955,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 76,
          name = "yellowTile31",
          type = "",
          shape = "rectangle",
          x = 237,
          y = 101.821,
          width = 0.363636,
          height = 0.357955,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 77,
          name = "yellowTile32",
          type = "",
          shape = "rectangle",
          x = 231.768,
          y = 18.7901,
          width = 0.363636,
          height = 0.357955,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 78,
          name = "yellowTile33",
          type = "",
          shape = "rectangle",
          x = 253.614,
          y = 39.0656,
          width = 0.363636,
          height = 0.357955,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 79,
          name = "yellowTile34",
          type = "",
          shape = "rectangle",
          x = 253.245,
          y = 55.2123,
          width = 0.363636,
          height = 0.357955,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 35,
      name = "player",
      visible = false,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      objects = {
        {
          id = 37,
          name = "player",
          type = "",
          shape = "rectangle",
          x = 128,
          y = 240,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 16,
      name = "blueTile",
      visible = false,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {
        ["numObjects"] = 17
      },
      objects = {
        {
          id = 3,
          name = "blueTile1",
          type = "",
          shape = "rectangle",
          x = 36.723,
          y = 172.854,
          width = 0.363636,
          height = 0.363636,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 4,
          name = "blueTile2",
          type = "",
          shape = "rectangle",
          x = 36.7745,
          y = 108.666,
          width = 0.5,
          height = 0.5,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 46,
          name = "blueTile3",
          type = "",
          shape = "rectangle",
          x = 37.287,
          y = 60.0999,
          width = 0.363636,
          height = 0.363636,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 47,
          name = "blueTile4",
          type = "",
          shape = "rectangle",
          x = 67.4744,
          y = 61.2296,
          width = 0.5,
          height = 0.5,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 48,
          name = "blueTile5",
          type = "",
          shape = "rectangle",
          x = 87.3125,
          y = 173.729,
          width = 0.5,
          height = 0.5,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 49,
          name = "blueTile6",
          type = "",
          shape = "rectangle",
          x = 86.375,
          y = 220.25,
          width = 0.5,
          height = 0.5,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 50,
          name = "blueTile7",
          type = "",
          shape = "rectangle",
          x = 135.688,
          y = 51.2292,
          width = 0.5,
          height = 0.5,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 51,
          name = "blueTile9",
          type = "",
          shape = "rectangle",
          x = 132.458,
          y = 172.375,
          width = 0.5,
          height = 0.5,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 52,
          name = "blueTile8",
          type = "",
          shape = "rectangle",
          x = 135.693,
          y = 115.28,
          width = 0.5,
          height = 0.5,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 80,
          name = "blueTile10",
          type = "",
          shape = "rectangle",
          x = 200.75,
          y = 221.932,
          width = 0.5,
          height = 0.5,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 81,
          name = "blueTile11",
          type = "",
          shape = "rectangle",
          x = 200.477,
          y = 162.841,
          width = 0.5,
          height = 0.5,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 82,
          name = "blueTile12",
          type = "",
          shape = "rectangle",
          x = 200.841,
          y = 116.295,
          width = 0.5,
          height = 0.5,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 83,
          name = "blueTile13",
          type = "",
          shape = "rectangle",
          x = 172.114,
          y = 50.6818,
          width = 0.5,
          height = 0.5,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 84,
          name = "blueTile14",
          type = "",
          shape = "rectangle",
          x = 235,
          y = 34.75,
          width = 0.5,
          height = 0.5,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 85,
          name = "blueTile15",
          type = "",
          shape = "rectangle",
          x = 236.523,
          y = 61.4205,
          width = 0.5,
          height = 0.5,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 86,
          name = "blueTile16",
          type = "",
          shape = "rectangle",
          x = 238,
          y = 147,
          width = 0.5,
          height = 0.5,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 87,
          name = "blueTile17",
          type = "",
          shape = "rectangle",
          x = 237,
          y = 169.875,
          width = 0.5,
          height = 0.5,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 21,
      name = "fruit",
      visible = false,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {
        ["numObjects"] = 34
      },
      objects = {
        {
          id = 5,
          name = "fruit1",
          type = "",
          shape = "rectangle",
          x = 119.255,
          y = 121.324,
          width = 0.1875,
          height = 0.1875,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 8,
          name = "fruit2",
          type = "",
          shape = "rectangle",
          x = 198.401,
          y = 120.501,
          width = 0.545455,
          height = 0.363636,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 11,
          name = "fruit3",
          type = "",
          shape = "rectangle",
          x = 87.753,
          y = 170.073,
          width = 0.363636,
          height = 0.545455,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 15,
          name = "fruit4",
          type = "",
          shape = "rectangle",
          x = 232.577,
          y = 151.287,
          width = 0.909091,
          height = 0.545455,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 16,
          name = "fruit5",
          type = "",
          shape = "rectangle",
          x = 106.745,
          y = 214.547,
          width = 0.545455,
          height = 0.545455,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 128,
          name = "fruit6",
          type = "",
          shape = "rectangle",
          x = 87.767,
          y = 254.045,
          width = 0.545455,
          height = 0.545455,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 129,
          name = "fruit7",
          type = "",
          shape = "rectangle",
          x = 66.5398,
          y = 221.165,
          width = 0.545455,
          height = 0.545455,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 130,
          name = "fruit8",
          type = "",
          shape = "rectangle",
          x = 39.5455,
          y = 205.545,
          width = 0.545455,
          height = 0.545455,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 131,
          name = "fruit9",
          type = "",
          shape = "rectangle",
          x = 21.7273,
          y = 173,
          width = 0.545455,
          height = 0.545455,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 132,
          name = "fruit10",
          type = "",
          shape = "rectangle",
          x = 33.8182,
          y = 146.364,
          width = 0.545455,
          height = 0.545455,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 133,
          name = "fruit11",
          type = "",
          shape = "rectangle",
          x = 33.9091,
          y = 130.364,
          width = 0.545455,
          height = 0.545455,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 134,
          name = "fruit12",
          type = "",
          shape = "rectangle",
          x = 18.8182,
          y = 99.3636,
          width = 0.545455,
          height = 0.545455,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 135,
          name = "fruit13",
          type = "",
          shape = "rectangle",
          x = 61,
          y = 98.8182,
          width = 0.545455,
          height = 0.545455,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 136,
          name = "fruit14",
          type = "",
          shape = "rectangle",
          x = 18.2727,
          y = 51,
          width = 0.545455,
          height = 0.545455,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 137,
          name = "fruit15",
          type = "",
          shape = "rectangle",
          x = 44.0909,
          y = 34.0909,
          width = 0.545455,
          height = 0.545455,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 138,
          name = "fruit16",
          type = "",
          shape = "rectangle",
          x = 75.7273,
          y = 18.6364,
          width = 0.545455,
          height = 0.545455,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 139,
          name = "fruit17",
          type = "",
          shape = "rectangle",
          x = 67.1818,
          y = 140.818,
          width = 0.545455,
          height = 0.545455,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 140,
          name = "fruit18",
          type = "",
          shape = "rectangle",
          x = 93.5455,
          y = 114.818,
          width = 0.545455,
          height = 0.545455,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 141,
          name = "fruit19",
          type = "",
          shape = "rectangle",
          x = 135.909,
          y = 18.0909,
          width = 0.545455,
          height = 0.545455,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 142,
          name = "fruit20",
          type = "",
          shape = "rectangle",
          x = 172.455,
          y = 34.2727,
          width = 0.545455,
          height = 0.545455,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 143,
          name = "fruit21",
          type = "",
          shape = "rectangle",
          x = 236.455,
          y = 19.3636,
          width = 0.545455,
          height = 0.545455,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 144,
          name = "fruit22",
          type = "",
          shape = "rectangle",
          x = 253.727,
          y = 38.8182,
          width = 0.545455,
          height = 0.545455,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 145,
          name = "fruit23",
          type = "",
          shape = "rectangle",
          x = 253.909,
          y = 56.8182,
          width = 0.545455,
          height = 0.545455,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 146,
          name = "fruit24",
          type = "",
          shape = "rectangle",
          x = 237.545,
          y = 100.455,
          width = 0.545455,
          height = 0.545455,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 147,
          name = "fruit25",
          type = "",
          shape = "rectangle",
          x = 237.909,
          y = 120.636,
          width = 0.545455,
          height = 0.545455,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 148,
          name = "fruit26",
          type = "",
          shape = "rectangle",
          x = 238.273,
          y = 135.727,
          width = 0.545455,
          height = 0.545455,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 149,
          name = "fruit27",
          type = "",
          shape = "rectangle",
          x = 215.909,
          y = 145.545,
          width = 0.545455,
          height = 0.545455,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 150,
          name = "fruit28",
          type = "",
          shape = "rectangle",
          x = 253.182,
          y = 146.818,
          width = 0.545455,
          height = 0.545455,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 151,
          name = "fruit29",
          type = "",
          shape = "rectangle",
          x = 252.636,
          y = 170.455,
          width = 0.545455,
          height = 0.545455,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 152,
          name = "fruit30",
          type = "",
          shape = "rectangle",
          x = 170.037,
          y = 114.284,
          width = 0.545455,
          height = 0.545455,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 153,
          name = "fruit31",
          type = "",
          shape = "rectangle",
          x = 200.016,
          y = 83.087,
          width = 0.545455,
          height = 0.545455,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 154,
          name = "fruit32",
          type = "",
          shape = "rectangle",
          x = 234.227,
          y = 220.977,
          width = 0.545455,
          height = 0.545455,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 155,
          name = "fruit33",
          type = "",
          shape = "rectangle",
          x = 198.977,
          y = 253.477,
          width = 0.545455,
          height = 0.545455,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 156,
          name = "fruit34",
          type = "",
          shape = "rectangle",
          x = 179.477,
          y = 214.477,
          width = 0.545455,
          height = 0.545455,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 27,
      name = "apple1",
      visible = true,
      opacity = 1,
      offsetx = 6.3144,
      offsety = -1.83712,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFo2AUjIJRMFLAd66BdsEoGAWjYLgDAHb2AQI="
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 28,
      name = "apple2",
      visible = true,
      opacity = 1,
      offsetx = 3.5644,
      offsety = -1.71212,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFo2AUjIJRMJLAd66BdsEoGAWjYDgDAHLyAQI="
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 29,
      name = "apple3",
      visible = true,
      opacity = 1,
      offsetx = 0.689397,
      offsety = -1.71212,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFo2AUjIJRMNLAd66BdsEoGAWjYLgCAG7uAQI="
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 30,
      name = "apple4",
      visible = true,
      opacity = 1,
      offsetx = -2.0606,
      offsety = -1.83712,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFo2AUjIJRMBLBd66BdsEoGAWjYDgCAGrqAQI="
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 31,
      name = "apple5",
      visible = true,
      opacity = 1,
      offsetx = -4.8106,
      offsety = -1.83712,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFo2AUjIJRMFLBd66BdsEoGAWjYLgBAGbmAQI="
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 41,
      name = "apple6",
      visible = true,
      opacity = 1,
      offsetx = -23.6818,
      offsety = -1.84091,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFo2AUjIJRMNLBd66BdsEoGAWjYLgAAF7eAQI="
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 56,
      name = "apple7",
      visible = true,
      opacity = 1,
      offsetx = 6.86364,
      offsety = 1.11364,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFo2AUjIJRQE3wnWugXTAKRsEoGAUDBwAToQEC"
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 57,
      name = "apple8",
      visible = true,
      opacity = 1,
      offsetx = 3.36364,
      offsety = 1.36364,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFo2AUjIJRQG3wnWugXTAKRsEoGAUDAwAPnQEC"
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 58,
      name = "apple9",
      visible = true,
      opacity = 1,
      offsetx = 0.613636,
      offsety = 1.23864,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFo2AUjIJRQAvwnWugXTAKRsEoGAX0BwALmQEC"
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 59,
      name = "apple10",
      visible = true,
      opacity = 1,
      offsetx = -2.63636,
      offsety = 0.988636,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFo2AUjIJRQCvwnWugXTAKRsEoGAX0BQAHlQEC"
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 60,
      name = "apple11",
      visible = true,
      opacity = 1,
      offsetx = -5.26136,
      offsety = 1.11364,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFo2AUjIJRQEvwnWugXTAKRsEoGAX0AwADkQEC"
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 61,
      name = "apple12",
      visible = true,
      opacity = 1,
      offsetx = -7.76136,
      offsety = 0.988636,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFo2AUjIJRQGvwnWugXTAKRsEoGAX0AQD/fgEC"
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 62,
      name = "apple13",
      visible = true,
      opacity = 1,
      offsetx = 7.36364,
      offsety = 4.11364,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFo2AUjIKhB75zDbQLRsEoGAWjYBRgAwCwPQEC"
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 63,
      name = "apple14",
      visible = true,
      opacity = 1,
      offsetx = 4.31818,
      offsety = 4.38636,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFo2AUjIKhCb5zDbQLRsEoGAWjYBSgAwCsOQEC"
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 64,
      name = "apple15",
      visible = true,
      opacity = 1,
      offsetx = 1.24432,
      offsety = 4.17614,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFo2AUjIKhC75zDbQLRsEoGAWjYBQgAwCoNQEC"
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 65,
      name = "apple16",
      visible = true,
      opacity = 1,
      offsetx = -1.68182,
      offsety = 4.02273,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFo2AUjIKhDb5zDbQLRsEoGAWjYBTAAACkMQEC"
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 66,
      name = "apple17",
      visible = true,
      opacity = 1,
      offsetx = -4.77273,
      offsety = 4.20455,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFo2AUjIKhD75zDbQLRsEoGAWjYBSAAACgLQEC"
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 67,
      name = "apple18",
      visible = true,
      opacity = 1,
      offsetx = -7.77273,
      offsety = 4.02273,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFo2AUjILhAb5zDbQLRsEoGAWjYBQAAJwpAQI="
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 68,
      name = "apple19",
      visible = true,
      opacity = 1,
      offsetx = 7.18182,
      offsety = 7.36364,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFo2AUjALs4DvXQLtgFIyCUTAKRsFQAwBM6AEC"
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 69,
      name = "apple20",
      visible = true,
      opacity = 1,
      offsetx = 4.31818,
      offsety = 7.38636,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFo2AUjALc4DvXQLtgFIyCUTAKRsFQAgBI5AEC"
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 70,
      name = "apple21",
      visible = true,
      opacity = 1,
      offsetx = 1.42614,
      offsety = 7.26705,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFo2AUjAL84DvXQLtgFIyCUTAKRsFQAQBE4AEC"
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 71,
      name = "apple22",
      visible = true,
      opacity = 1,
      offsetx = -1.59091,
      offsety = 7.05682,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFo2AUjALC4DvXQLtgFIyCUTAKRsFQAABA3AEC"
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 72,
      name = "apple23",
      visible = true,
      opacity = 1,
      offsetx = -4.76136,
      offsety = 7.11364,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFo2AUjALiwHeugXbBKBgFo2AUjILBDgA82AEC"
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 73,
      name = "apple24",
      visible = true,
      opacity = 1,
      offsetx = -7.76136,
      offsety = 6.98864,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFo2AUjALiwXeugXbBKBgFo2AUjILBDAA41AEC"
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 74,
      name = "apple25",
      visible = true,
      opacity = 1,
      offsetx = 7.36364,
      offsety = 10.2386,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFo2AUDCT4zjXQLhgFo2AUjIJRMAqoBwDphAEC"
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 75,
      name = "apple26",
      visible = true,
      opacity = 1,
      offsetx = 4.28409,
      offsety = 10.3295,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFo2AUDDT4zjXQLhgFo2AUjIJRMAqoAwDlgAEC"
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 76,
      name = "apple27",
      visible = true,
      opacity = 1,
      offsetx = 1.30114,
      offsety = 10.3011,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFo2AUDAbwnWugXTAKRsEoGAWjYBRQDgDhfAEC"
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 77,
      name = "apple28",
      visible = true,
      opacity = 1,
      offsetx = -1.71591,
      offsety = 10.0568,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFo2AUDBbwnWugXTAKRsEoGAWjYBRQBgDdeAEC"
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 78,
      name = "apple29",
      visible = true,
      opacity = 1,
      offsetx = -4.76136,
      offsety = 10.2386,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFo2AUDCbwnWugXTAKRsEoGAWjYBSQDwDZdAEC"
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 79,
      name = "apple30",
      visible = true,
      opacity = 1,
      offsetx = -7.76136,
      offsety = 9.98864,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFo2AUDDbwnWugXTAKRsEoGAWjYBSQBwDVcAEC"
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 80,
      name = "apple31",
      visible = true,
      opacity = 1,
      offsetx = 4.23864,
      offsety = 13.3636,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFo2BkgO9cA+2CUTAKRsEoGAWjYPgDAIIrAQI="
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 81,
      name = "apple32",
      visible = true,
      opacity = 1,
      offsetx = 1.28409,
      offsety = 13.3295,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFo2DkgO9cA+2CUTAKRsEoGAWjYHgDAH4nAQI="
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 83,
      name = "apple33",
      visible = true,
      opacity = 1,
      offsetx = -1.69886,
      offsety = 13.3011,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFo2Bkge9cA+2CUTAKRsEoGAWjYPgCAHojAQI="
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 17,
      id = 84,
      name = "apple34",
      visible = true,
      opacity = 1,
      offsetx = -4.59091,
      offsety = 13.3523,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFo2Dkge9cA+2CUTAKRsEoGAWjYHgCAHYfAQI="
    }
  }
}
